import Mathlib

/-!
# Bapat-Lal q-permanent monotonicity: standalone Lean4Web proof

Generated by lean/scripts/make_lean4web.py from the FC-compatible proof.
Tested with Lean v4.35.0-rc3 and Mathlib
5e0c4e5239cb0a2d86d68a884bf52cfd963fce22.
The final theorem is BapatLal.qPermanentMonotonicity.
No local project imports or Formal Conjectures dependency are needed.
-/

-- FC's answer(False) elaborates to False. This identity macro preserves that type.
macro "answer(" t:term ")" : term => pure t

#eval Lean.versionString

-- Source: Bapat/Statement.lean
/-! # Definitions copied from FClikelean/QPermanentMonotonicity.lean -/

open scoped BigOperators

/-- The number of inversions of a permutation of an ordered finite set. -/
def Equiv.Perm.inversionCount {n : ℕ} (σ : Equiv.Perm (Fin n)) : ℕ :=
  (Finset.univ.filter fun p : Fin n × Fin n => p.1 < p.2 ∧ σ p.2 < σ p.1).card

/-- The q-permanent, with a real deformation parameter and complex values. -/
noncomputable def Matrix.qPermanent {n : ℕ} (A : Matrix (Fin n) (Fin n) ℂ) (q : ℝ) : ℂ :=
  ∑ σ : Equiv.Perm (Fin n), (q ^ σ.inversionCount : ℝ) * ∏ i, A i (σ i)


-- Source: Bapat/ColorCount.lean
/-!
# Factorial multiplicities for two-coordinate assignments

The rank-two coefficient formula counts permutations matching two colourings.
Instead of counting them from scratch, use the existing equivalence between
a function stabilizer and permutations of its fibres.
-/

namespace Bapat

noncomputable section

theorem finTwo_cases (c : Fin 2) : c = 0 ∨ c = 1 := by fin_cases c <;> simp

def colorCount {n : ℕ} (f : Fin n → Fin 2) (c : Fin 2) : ℕ :=
  Fintype.card {i // f i = c}

theorem colorCount_zero {n : ℕ} (f : Fin n → Fin 2) :
    colorCount f 0 = n - colorCount f 1 := by
  classical
  have hiff : ∀ i, f i = 0 ↔ ¬ f i = 1 := by
    intro i
    rcases finTwo_cases (f i) with h | h <;> simp [h]
  calc
    colorCount f 0 = Fintype.card {i // ¬ f i = 1} :=
      Fintype.card_congr (Equiv.subtypeEquivRight hiff)
    _ = n - colorCount f 1 := by simp [Fintype.card_subtype_compl, colorCount]

theorem colorCount_comp {n : ℕ} (f : Fin n → Fin 2)
    (σ : Equiv.Perm (Fin n)) (c : Fin 2) : colorCount (f ∘ σ) c = colorCount f c := by
  classical
  exact Fintype.card_congr (Equiv.subtypeEquiv σ (fun _ => Iff.rfl))

/-- A compatible permutation exists when the two coordinate counts agree. -/
theorem exists_colorMatching {n : ℕ} (f g : Fin n → Fin 2)
    (h : colorCount f 1 = colorCount g 1) :
    ∃ σ : Equiv.Perm (Fin n), f ∘ σ = g := by
  classical
  have hc : ∀ c, colorCount g c = colorCount f c := by
    intro c
    rcases finTwo_cases c with heq | heq
    · simpa [heq, colorCount_zero] using congrArg (n - ·) h.symm
    · simpa [heq] using h.symm
  let e (c : Fin 2) : {i // g i = c} ≃ {i // f i = c} :=
    Fintype.equivOfCardEq (hc c)
  let σ : Equiv.Perm (Fin n) :=
    (Equiv.sigmaFiberEquiv g).symm.trans
      ((Equiv.sigmaCongrRight e).trans (Equiv.sigmaFiberEquiv f))
  refine ⟨σ, funext fun i => ?_⟩
  exact (e (g i) ⟨i, rfl⟩).property

/-- A single matching identifies all matchings with the function stabilizer. -/
def colorMatchingEquiv {n : ℕ} {ι : Type*} (f g : Fin n → ι)
    (σ₀ : Equiv.Perm (Fin n)) (h₀ : f ∘ σ₀ = g) :
    {σ : Equiv.Perm (Fin n) // f ∘ σ = g} ≃
      {τ : Equiv.Perm (Fin n) // f ∘ τ = f} where
  toFun σ := ⟨σ.val * σ₀.symm, by
    funext i
    change f (σ.val (σ₀.symm i)) = f i
    calc
      _ = g (σ₀.symm i) := congrFun σ.property _
      _ = f i := by rw [← h₀]; simp⟩
  invFun τ := ⟨τ.val * σ₀, by
    funext i
    change f (τ.val (σ₀ i)) = g i
    calc
      _ = f (σ₀ i) := congrFun τ.property _
      _ = g i := congrFun h₀ _⟩
  left_inv σ := by
    apply Subtype.ext
    apply Equiv.ext
    intro i
    simp [Equiv.Perm.mul_apply]
  right_inv τ := by
    apply Subtype.ext
    apply Equiv.ext
    intro i
    simp [Equiv.Perm.mul_apply]

/-- The k!(n-k)! multiplicity in the permanent coefficient formula. -/
theorem colorMatching_card {n : ℕ} (f g : Fin n → Fin 2)
    (h : colorCount f 1 = colorCount g 1) :
    Fintype.card {σ : Equiv.Perm (Fin n) // f ∘ σ = g} =
      (colorCount f 1).factorial * (n - colorCount f 1).factorial := by
  classical
  obtain ⟨σ₀, h₀⟩ := exists_colorMatching f g h
  rw [Fintype.card_congr (colorMatchingEquiv f g σ₀ h₀),
    DomMulAct.stabilizer_card, Fin.prod_univ_two]
  change (colorCount f 0).factorial * (colorCount f 1).factorial = _
  rw [colorCount_zero, Nat.mul_comm]

theorem colorMatching_card_ite {n : ℕ} (f g : Fin n → Fin 2) :
    Fintype.card {σ : Equiv.Perm (Fin n) // f ∘ σ = g} =
      if colorCount f 1 = colorCount g 1 then
        (colorCount f 1).factorial * (n - colorCount f 1).factorial
      else 0 := by
  classical
  by_cases h : colorCount f 1 = colorCount g 1
  · simpa [h] using colorMatching_card f g h
  · have hempty : IsEmpty {σ : Equiv.Perm (Fin n) // f ∘ σ = g} := ⟨fun σ => by
      have heq := colorCount_comp f σ.val 1
      rw [σ.property] at heq
      exact h heq.symm⟩
    simp [h]

#print axioms colorMatching_card_ite

end
end Bapat


-- Source: Bapat/Basic.lean
/-!
# The ordered q-permanent and a shortcut at the endpoint

The real-valued definition is the real part of the usual complex q-permanent.
For Hermitian matrices the usual polynomial is real-valued. Taking the real part
avoids imposing an order on arbitrary complex polynomial values.

References: Bapat–Lal (1994), doi:10.1016/0024-3795(94)90497-9;
da Fonseca (2018), arXiv:1804.02231, Conjecture 1.
-/

open scoped BigOperators ComplexOrder

namespace Bapat

noncomputable section

/-- Number of inversions, with the order on `Fin n` fixed. -/
def inversions {n : ℕ} (σ : Equiv.Perm (Fin n)) : ℕ :=
  (Finset.univ.filter fun ij : Fin n × Fin n => ij.1 < ij.2 ∧ σ ij.2 < σ ij.1).card

/-- Real part of the permutation monomial. -/
def termRe {n : ℕ} (A : Matrix (Fin n) (Fin n) ℂ) (σ : Equiv.Perm (Fin n)) : ℝ :=
  (∏ i, A i (σ i)).re

/-- Real part of the ordered q-permanent. -/
def qPermanent {n : ℕ} (A : Matrix (Fin n) (Fin n) ℂ) (q : ℝ) : ℝ :=
  ∑ σ : Equiv.Perm (Fin n), q ^ inversions σ * termRe A σ

/-- Explicit finite sum for the derivative at `q = 1`. -/
def endpointDerivative {n : ℕ} (A : Matrix (Fin n) (Fin n) ℂ) : ℝ :=
  ∑ σ : Equiv.Perm (Fin n), (inversions σ : ℝ) * termRe A σ

/-- The original universal monotonicity assertion. -/
def BapatMonotonicity : Prop :=
  ∀ (n : ℕ) (A : Matrix (Fin n) (Fin n) ℂ),
    A.PosDef → ¬ A.IsDiag → StrictMonoOn (qPermanent A) (Set.Icc (-1) 1)

theorem hasDerivAt_qPermanent_one {n : ℕ} (A : Matrix (Fin n) (Fin n) ℂ) :
    HasDerivAt (qPermanent A) (endpointDerivative A) 1 := by
  classical
  apply HasDerivAt.fun_sum
  intro σ _
  simpa using ((hasDerivAt_id (1 : ℝ)).pow (inversions σ)).mul_const (termRe A σ)

/-- A negative derivative even at the right endpoint rules out monotonicity. -/
theorem not_monotoneOn_Icc_of_hasDerivAt_neg {f : ℝ → ℝ} {d a b : ℝ}
    (hab : a < b) (hd : HasDerivAt f d b) (hneg : d < 0) :
    ¬ MonotoneOn f (Set.Icc a b) := by
  intro hmono
  have huniq : UniqueDiffWithinAt ℝ (Set.Icc a b) b :=
    (uniqueDiffOn_Icc hab) b ⟨hab.le, le_rfl⟩
  have heq := hd.hasDerivWithinAt.derivWithin huniq
  have hnonneg := hmono.derivWithin_nonneg (x := b)
  rw [heq] at hnonneg
  exact (not_lt_of_ge hnonneg) hneg

theorem not_strictMonoOn_of_endpoint_negative {n : ℕ}
    (A : Matrix (Fin n) (Fin n) ℂ) (hneg : endpointDerivative A < 0) :
    ¬ StrictMonoOn (qPermanent A) (Set.Icc (-1) 1) := by
  intro hmono
  exact not_monotoneOn_Icc_of_hasDerivAt_neg (by norm_num)
    (hasDerivAt_qPermanent_one A) hneg hmono.monotoneOn

theorem endpointDerivative_perturb_continuous {n : ℕ}
    (H : Matrix (Fin n) (Fin n) ℂ) :
    Continuous (fun ε : ℝ => endpointDerivative (H + ε • 1)) := by
  unfold endpointDerivative termRe
  fun_prop

/-- No explicit perturbation size or second derivative bound is needed. -/
theorem exists_positive_perturbation_negative {n : ℕ}
    (H : Matrix (Fin n) (Fin n) ℂ) (hneg : endpointDerivative H < 0) :
    ∃ ε : ℝ, 0 < ε ∧ endpointDerivative (H + ε • 1) < 0 := by
  have hcont := (endpointDerivative_perturb_continuous H).continuousAt (x := 0)
  have hnear : ∀ᶠ ε : ℝ in nhds 0, endpointDerivative (H + ε • 1) < 0 :=
    hcont.eventually_lt continuousAt_const (by simpa using hneg)
  exact hnear.exists_gt

theorem positive_perturbation_posDef {n : ℕ}
    (H : Matrix (Fin n) (Fin n) ℂ) (hH : H.PosSemidef)
    {ε : ℝ} (hε : 0 < ε) : (H + ε • 1).PosDef :=
  Matrix.PosDef.posSemidef_add hH
    ((Matrix.PosDef.one : (1 : Matrix (Fin n) (Fin n) ℂ).PosDef).smul hε)

/-- The analytic part of the disproof reduces to one endpoint inequality. -/
theorem not_bapatMonotonicity_of_psd_endpoint_negative {n : ℕ}
    (H : Matrix (Fin n) (Fin n) ℂ) (hH : H.PosSemidef)
    (hneg : endpointDerivative H < 0)
    (hoff : ∃ i j : Fin n, i ≠ j ∧ H i j ≠ 0) : ¬ BapatMonotonicity := by
  obtain ⟨ε, hε, hnegε⟩ := exists_positive_perturbation_negative H hneg
  have hpd := positive_perturbation_posDef H hH hε
  have hnd : ¬ (H + ε • 1).IsDiag := by
    obtain ⟨i, j, hij, hval⟩ := hoff
    intro hdiag
    have hzero := hdiag hij
    exact hval (by simpa [Matrix.add_apply, Matrix.smul_apply, Matrix.one_apply, hij] using hzero)
  intro hconj
  exact not_strictMonoOn_of_endpoint_negative (H + ε • 1) hnegε
    (hconj n _ hpd hnd)

#print axioms not_bapatMonotonicity_of_psd_endpoint_negative

end
end Bapat


-- Source: Bapat/PermutationReality.lean
/-!
# Permutation inversion and the real-valued Hermitian q-permanent

The real-part definition used by the analytic reduction agrees with the usual
complex q-permanent on every Hermitian matrix, for every real q.
-/

open scoped BigOperators

namespace Bapat

noncomputable section

theorem inversions_symm {n : ℕ} (σ : Equiv.Perm (Fin n)) :
    inversions σ.symm = inversions σ := by
  classical
  have h : inversions σ = inversions σ.symm := by
    unfold inversions
    apply Finset.card_bij (fun p _ => (σ p.2, σ p.1))
    · intro p hp
      simp only [Finset.mem_filter, Finset.mem_univ, true_and] at hp ⊢
      exact ⟨hp.2, by simpa using hp.1⟩
    · intro p _ r _ heq
      apply Prod.ext
      · exact σ.injective (congrArg Prod.snd heq)
      · exact σ.injective (congrArg Prod.fst heq)
    · intro r hr
      refine ⟨(σ.symm r.2, σ.symm r.1), ?_, ?_⟩
      · simp only [Finset.mem_filter, Finset.mem_univ, true_and] at hr ⊢
        exact ⟨hr.2, by simpa using hr.1⟩
      · simp
  exact h.symm

def complexTerm {n : ℕ} (A : Matrix (Fin n) (Fin n) ℂ)
    (σ : Equiv.Perm (Fin n)) : ℂ := ∏ i, A i (σ i)

theorem star_complexTerm {n : ℕ} (A : Matrix (Fin n) (Fin n) ℂ)
    (hA : A.IsHermitian) (σ : Equiv.Perm (Fin n)) :
    star (complexTerm A σ) = complexTerm A σ.symm := by
  classical
  simp only [complexTerm, star_prod]
  exact Fintype.prod_equiv σ _ _ (fun i => by simpa using hA.apply (σ i) i)

def complexQPermanent {n : ℕ} (A : Matrix (Fin n) (Fin n) ℂ) (q : ℝ) : ℂ :=
  ∑ σ : Equiv.Perm (Fin n), (q ^ inversions σ : ℝ) * complexTerm A σ

theorem complexQPermanent_re {n : ℕ} (A : Matrix (Fin n) (Fin n) ℂ) (q : ℝ) :
    (complexQPermanent A q).re = qPermanent A q := by
  simp only [complexQPermanent, Complex.re_sum, Complex.mul_re,
    Complex.ofReal_re, Complex.ofReal_im, zero_mul, sub_zero,
    qPermanent, complexTerm, termRe]

theorem star_complexQPermanent {n : ℕ} (A : Matrix (Fin n) (Fin n) ℂ)
    (hA : A.IsHermitian) (q : ℝ) : star (complexQPermanent A q) = complexQPermanent A q := by
  classical
  unfold complexQPermanent
  simp only [star_sum, star_mul, star_complexTerm A hA,
    Complex.star_def, Complex.conj_ofReal]
  have hbij : Function.Bijective (fun σ : Equiv.Perm (Fin n) => σ.symm) :=
    (show Function.Involutive (fun σ : Equiv.Perm (Fin n) => σ.symm) from
      fun σ => σ.symm_symm).bijective
  simpa only [inversions_symm, mul_comm] using hbij.sum_comp
    (fun σ : Equiv.Perm (Fin n) => (q ^ inversions σ : ℝ) * complexTerm A σ)

theorem complexQPermanent_im {n : ℕ} (A : Matrix (Fin n) (Fin n) ℂ)
    (hA : A.IsHermitian) (q : ℝ) : (complexQPermanent A q).im = 0 := by
  have h := congrArg Complex.im (star_complexQPermanent A hA q)
  simp only [Complex.star_def, Complex.conj_im] at h
  linarith

/-- This establishes the exact correspondence with the statement in the manuscript. -/
theorem complexQPermanent_eq_real {n : ℕ} (A : Matrix (Fin n) (Fin n) ℂ)
    (hA : A.IsHermitian) (q : ℝ) : complexQPermanent A q = (qPermanent A q : ℂ) := by
  apply Complex.ext
  · simpa using complexQPermanent_re A q
  · simpa using complexQPermanent_im A hA q

theorem complexQPermanent_one {n : ℕ} (A : Matrix (Fin n) (Fin n) ℂ) :
    complexQPermanent A 1 = A.permanent := by
  classical
  calc
    complexQPermanent A 1 = A.transpose.permanent := by
      simp [complexQPermanent, complexTerm, Matrix.permanent, Matrix.transpose_apply]
    _ = A.permanent := Matrix.permanent_transpose A

theorem qPermanent_one {n : ℕ} (A : Matrix (Fin n) (Fin n) ℂ) :
    qPermanent A 1 = A.permanent.re := by
  rw [← complexQPermanent_re, complexQPermanent_one]

#print axioms complexQPermanent_eq_real

end
end Bapat


-- Source: Bapat/RankTwoPermanent.lean
/-! # Two-coordinate polynomial coefficients and the Gram permanent -/

open scoped BigOperators

namespace Bapat

noncomputable section

def colorMonomial {n : ℕ} (V : Matrix (Fin n) (Fin 2) ℂ) (f : Fin n → Fin 2) : ℂ :=
  ∏ i, V i (f i)

def colorCoefficient {n : ℕ} (V : Matrix (Fin n) (Fin 2) ℂ) (k : ℕ) : ℂ :=
  ∑ f : Fin n → Fin 2, if colorCount f 1 = k then colorMonomial V f else 0

def factorPolynomial {n : ℕ} (V : Matrix (Fin n) (Fin 2) ℂ) : Polynomial ℂ :=
  ∏ i, (Polynomial.C (V i 0) + Polynomial.C (V i 1) * Polynomial.X)

theorem colorCount_eq_sum {n : ℕ} (f : Fin n → Fin 2) :
    colorCount f 1 = ∑ i, if f i = 1 then 1 else 0 := by
  classical
  rw [colorCount, Fintype.card_subtype, Finset.card_filter]

theorem factorPolynomial_colorSum {n : ℕ} (V : Matrix (Fin n) (Fin 2) ℂ) :
    factorPolynomial V = ∑ f : Fin n → Fin 2,
      Polynomial.C (colorMonomial V f) * Polynomial.X ^ colorCount f 1 := by
  classical
  have h := Fintype.prod_sum (fun i (c : Fin 2) =>
    Polynomial.C (V i c) * Polynomial.X ^ (if c = 1 then 1 else 0))
  have hprod : ∀ f : Fin n → Fin 2,
      (∏ i, Polynomial.C (V i (f i)) * Polynomial.X ^ (if f i = 1 then 1 else 0)) =
        Polynomial.C (colorMonomial V f) * Polynomial.X ^ colorCount f 1 := by
    intro f
    rw [Finset.prod_mul_distrib, Finset.prod_pow_eq_pow_sum,
      ← colorCount_eq_sum, ← map_prod]
    rfl
  have hzero : (0 : Fin 2) ≠ 1 := by decide
  simp only [Fin.sum_univ_two, ite_eq_right hzero, ite_true, pow_zero, pow_one, mul_one] at h
  simpa only [factorPolynomial, hprod] using h

theorem factorPolynomial_coeff {n : ℕ} (V : Matrix (Fin n) (Fin 2) ℂ) (k : ℕ) :
    (factorPolynomial V).coeff k = colorCoefficient V k := by
  rw [factorPolynomial_colorSum]
  simp [Polynomial.finsetSum_coeff, colorCoefficient, eq_comm]

theorem sum_color_permutations {n : ℕ} (V : Matrix (Fin n) (Fin 2) ℂ)
    (f : Fin n → Fin 2) :
    (∑ σ : Equiv.Perm (Fin n), colorMonomial V (f ∘ σ)) =
      ∑ g : Fin n → Fin 2,
        (if colorCount f 1 = colorCount g 1 then
          (colorCount f 1).factorial * (n - colorCount f 1).factorial else 0 : ℕ) *
            colorMonomial V g := by
  classical
  have h := Fintype.sum_fiberwise' (fun σ : Equiv.Perm (Fin n) => f ∘ σ)
    (colorMonomial V)
  simpa [colorMatching_card_ite, nsmul_eq_mul] using h.symm

theorem colorMonomial_permute {n : ℕ} (V : Matrix (Fin n) (Fin 2) ℂ)
    (f : Fin n → Fin 2) (σ : Equiv.Perm (Fin n)) :
    (∏ i, V (σ i) (f i)) = colorMonomial V (f ∘ σ.symm) := by
  classical
  exact Fintype.prod_equiv σ _ _ (fun i => by simp)

theorem gram_permanent_colorSum {n : ℕ} (U W : Matrix (Fin n) (Fin 2) ℂ) :
    (U * W.conjTranspose).permanent =
      ∑ f : Fin n → Fin 2,
        (∑ g : Fin n → Fin 2,
          (if colorCount f 1 = colorCount g 1 then
            (colorCount f 1).factorial * (n - colorCount f 1).factorial else 0 : ℕ) *
              colorMonomial U g) * star (colorMonomial W f) := by
  classical
  unfold Matrix.permanent
  simp only [Matrix.mul_apply, Matrix.conjTranspose_apply]
  simp_rw [Fintype.prod_sum, Finset.prod_mul_distrib, ← star_prod,
    colorMonomial_permute]
  change (∑ σ : Equiv.Perm (Fin n), ∑ f : Fin n → Fin 2,
    colorMonomial U (f ∘ σ.symm) * star (colorMonomial W f)) = _
  rw [Finset.sum_comm]
  apply Finset.sum_congr rfl
  intro f _
  rw [← Finset.sum_mul]
  have hinv : (∑ σ : Equiv.Perm (Fin n), colorMonomial U (f ∘ σ.symm)) =
      ∑ σ : Equiv.Perm (Fin n), colorMonomial U (f ∘ σ) :=
    (show Function.Involutive (fun σ : Equiv.Perm (Fin n) => σ.symm) from
      fun σ => σ.symm_symm).bijective.sum_comp (fun σ => colorMonomial U (f ∘ σ))
  rw [hinv, sum_color_permutations]

theorem colorCount_le {n : ℕ} (f : Fin n → Fin 2) : colorCount f 1 ≤ n := by
  classical
  simpa [colorCount] using Fintype.card_subtype_le (fun i : Fin n => f i = 1)

def colorDegree {n : ℕ} (f : Fin n → Fin 2) : Fin (n + 1) :=
  ⟨colorCount f 1, Nat.lt_succ_of_le (colorCount_le f)⟩

theorem gram_permanent_coefficients {n : ℕ} (U W : Matrix (Fin n) (Fin 2) ℂ) :
    (U * W.conjTranspose).permanent = ∑ k : Fin (n + 1),
      ((k.val.factorial * (n - k.val).factorial : ℕ) : ℂ) *
        (factorPolynomial U).coeff k.val * star ((factorPolynomial W).coeff k.val) := by
  classical
  rw [gram_permanent_colorSum]
  have hinner : ∀ f : Fin n → Fin 2,
      (∑ g : Fin n → Fin 2,
        (if colorCount f 1 = colorCount g 1 then
          (colorCount f 1).factorial * (n - colorCount f 1).factorial else 0 : ℕ) *
            colorMonomial U g) =
      ((colorCount f 1).factorial * (n - colorCount f 1).factorial : ℕ) *
        colorCoefficient U (colorCount f 1) := by
    intro f
    simp [colorCoefficient, Finset.mul_sum, mul_ite, eq_comm]
  simp_rw [hinner]
  rw [← Finset.sum_fiberwise Finset.univ colorDegree]
  simp_rw [factorPolynomial_coeff]
  apply Finset.sum_congr rfl
  intro k _
  rw [Finset.sum_filter]
  simp only [colorCoefficient, star_sum, apply_ite, star_zero,
    Finset.mul_sum, Finset.sum_mul, ite_mul]
  apply Finset.sum_congr rfl
  intro f _
  have hiff : colorDegree f = k ↔ colorCount f 1 = k.val := Fin.ext_iff
  by_cases hf : colorCount f 1 = k.val <;> simp [hiff, hf]

#print axioms gram_permanent_coefficients

end
end Bapat


-- Source: Bapat/PairMinorIdentity.lean
/-!
# The endpoint identity using paired permutations

We index the complementary bijections by full permutations with ascending images
of the two selected rows. This avoids constructing submatrix index equivalences.
Each ordered row pair contributes a 2-by-2 determinant times the complementary
product. Swapping its two rows pairs ascents with descents.
-/

open scoped BigOperators

namespace Bapat

noncomputable section

def rowPairs (n : ℕ) : Finset (Fin n × Fin n) :=
  Finset.univ.filter fun p => p.1 < p.2

theorem inversions_eq_filterCard {n : ℕ} (σ : Equiv.Perm (Fin n)) :
    (rowPairs n |>.filter fun p => σ p.2 < σ p.1).card = inversions σ := by
  classical
  simp [rowPairs, inversions, Finset.filter_filter]

def remainingProduct {n : ℕ} (A : Matrix (Fin n) (Fin n) ℂ)
    (σ : Equiv.Perm (Fin n)) (i j : Fin n) : ℂ :=
  ∏ k ∈ (Finset.univ.erase i).erase j, A k (σ k)

theorem complexTerm_split {n : ℕ} (A : Matrix (Fin n) (Fin n) ℂ)
    (σ : Equiv.Perm (Fin n)) (i j : Fin n) (hij : i ≠ j) :
    complexTerm A σ = A i (σ i) * A j (σ j) * remainingProduct A σ i j := by
  classical
  have hj : j ∈ (Finset.univ : Finset (Fin n)).erase i := by simp [hij.symm]
  unfold complexTerm remainingProduct
  rw [← Finset.mul_prod_erase _ _ (Finset.mem_univ i),
    ← Finset.mul_prod_erase _ _ hj]
  ring

theorem remainingProduct_swap {n : ℕ} (A : Matrix (Fin n) (Fin n) ℂ)
    (σ : Equiv.Perm (Fin n)) (i j : Fin n) :
    remainingProduct A (σ * Equiv.swap i j) i j = remainingProduct A σ i j := by
  classical
  apply Finset.prod_congr rfl
  intro k hk
  have hkj := Finset.ne_of_mem_erase hk
  have hki := Finset.ne_of_mem_erase (Finset.mem_of_mem_erase hk)
  simp only [Equiv.Perm.mul_apply, Equiv.swap_apply_of_ne_of_ne hki hkj]

def pairMinorContribution {n : ℕ} (A : Matrix (Fin n) (Fin n) ℂ)
    (i j : Fin n) (σ : Equiv.Perm (Fin n)) : ℂ :=
  if σ i < σ j then
    (A i (σ i) * A j (σ j) - A i (σ j) * A j (σ i)) *
      remainingProduct A σ i j
  else 0

theorem pairMinorContribution_eq {n : ℕ} (A : Matrix (Fin n) (Fin n) ℂ)
    (i j : Fin n) (hij : i ≠ j) (σ : Equiv.Perm (Fin n)) :
    pairMinorContribution A i j σ =
      (if σ i < σ j then complexTerm A σ else 0) -
        (if σ i < σ j then complexTerm A (σ * Equiv.swap i j) else 0) := by
  classical
  by_cases h : σ i < σ j
  · simp only [pairMinorContribution, ite_eq_left h]
    rw [complexTerm_split A σ i j hij,
      complexTerm_split A (σ * Equiv.swap i j) i j hij, remainingProduct_swap]
    simp only [Equiv.Perm.mul_apply, Equiv.swap_apply_left, Equiv.swap_apply_right]
    ring
  · simp [pairMinorContribution, h]

theorem ascent_swapped_sum {n : ℕ} (A : Matrix (Fin n) (Fin n) ℂ)
    (i j : Fin n) :
    (∑ σ : Equiv.Perm (Fin n),
      if σ i < σ j then complexTerm A (σ * Equiv.swap i j) else 0) =
      ∑ σ : Equiv.Perm (Fin n), if σ j < σ i then complexTerm A σ else 0 := by
  classical
  simpa only [Equiv.Perm.mul_apply, Equiv.swap_apply_left, Equiv.swap_apply_right] using
    (Group.mulRight_bijective (Equiv.swap i j)).sum_comp
      (fun σ : Equiv.Perm (Fin n) => if σ j < σ i then complexTerm A σ else 0)

theorem pairMinor_sum {n : ℕ} (A : Matrix (Fin n) (Fin n) ℂ)
    (i j : Fin n) (hij : i ≠ j) :
    (∑ σ : Equiv.Perm (Fin n), pairMinorContribution A i j σ) =
      ∑ σ : Equiv.Perm (Fin n),
        (complexTerm A σ - 2 * (if σ j < σ i then complexTerm A σ else 0)) := by
  classical
  simp_rw [pairMinorContribution_eq A i j hij]
  rw [Finset.sum_sub_distrib, ascent_swapped_sum, ← Finset.sum_sub_distrib]
  apply Finset.sum_congr rfl
  intro σ _
  have hne : σ i ≠ σ j := fun h => hij (σ.injective h)
  rcases lt_or_gt_of_ne hne with h | h
  · simp [h, not_lt_of_ge h.le]
  · simp [h, not_lt_of_ge h.le]
    ring

/-- The minors are represented by ascending images and complementary bijections. -/
def pairMinorSum {n : ℕ} (A : Matrix (Fin n) (Fin n) ℂ) : ℂ :=
  ∑ p ∈ rowPairs n, ∑ σ : Equiv.Perm (Fin n), pairMinorContribution A p.1 p.2 σ

def complexEndpointDerivative {n : ℕ} (A : Matrix (Fin n) (Fin n) ℂ) : ℂ :=
  ∑ σ : Equiv.Perm (Fin n), (inversions σ : ℂ) * complexTerm A σ

theorem descent_pair_sum {n : ℕ} (A : Matrix (Fin n) (Fin n) ℂ)
    (σ : Equiv.Perm (Fin n)) :
    (∑ p ∈ rowPairs n, if σ p.2 < σ p.1 then complexTerm A σ else 0) =
      (inversions σ : ℂ) * complexTerm A σ := by
  classical
  rw [← Finset.sum_filter]
  simp [inversions_eq_filterCard, nsmul_eq_mul]

theorem pairMinorSum_eq {n : ℕ} (A : Matrix (Fin n) (Fin n) ℂ) :
    pairMinorSum A = (rowPairs n).card * complexQPermanent A 1 -
      2 * complexEndpointDerivative A := by
  classical
  unfold pairMinorSum
  have hpair : ∀ p ∈ rowPairs n,
      (∑ σ : Equiv.Perm (Fin n), pairMinorContribution A p.1 p.2 σ) =
        ∑ σ : Equiv.Perm (Fin n),
          (complexTerm A σ - 2 * (if σ p.2 < σ p.1 then complexTerm A σ else 0)) := by
    intro p hp
    exact pairMinor_sum A p.1 p.2 (Finset.mem_filter.mp hp).2.ne
  simp_rw [Finset.sum_congr rfl hpair]
  rw [Finset.sum_comm]
  simp_rw [Finset.sum_sub_distrib, ← Finset.mul_sum, descent_pair_sum]
  simp [complexQPermanent, complexEndpointDerivative, Finset.mul_sum, nsmul_eq_mul]

/-- The general matrix derivative identity, before the rank-two norm calculation. -/
theorem endpointDerivative_pairMinorSum {n : ℕ} (A : Matrix (Fin n) (Fin n) ℂ) :
    2 * endpointDerivative A = (rowPairs n).card * qPermanent A 1 - (pairMinorSum A).re := by
  have h : 2 * complexEndpointDerivative A =
      (rowPairs n).card * complexQPermanent A 1 - pairMinorSum A := by
    rw [pairMinorSum_eq]
    ring
  have hre := congrArg Complex.re h
  simpa [complexEndpointDerivative, endpointDerivative, complexTerm, termRe,
    complexQPermanent_re] using hre

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
theorem rowPairs_144_card : (rowPairs 144).card = 10296 := by decide +kernel

#print axioms endpointDerivative_pairMinorSum
#print axioms rowPairs_144_card

end
end Bapat


-- Source: Bapat/Certificate.lean
/-!
# Exact arithmetic for the ordered Bapat–Lal certificate

The arithmetic is checked by Lean's kernel. This module does not yet identify
its coefficient recurrence with the permutation definition of the q-permanent.
Source: ../01_Bapat元予想の反例_144次/展開済み/bapat_lal_certificate.json
-/

namespace Bapat.Certificate

abbrev Gaussian := Int × Int

def zero : Gaussian := (0, 0)
def add (x y : Gaussian) : Gaussian := (x.1 + y.1, x.2 + y.2)
def mul (x y : Gaussian) : Gaussian :=
  (x.1 * y.1 - x.2 * y.2, x.1 * y.2 + x.2 * y.1)
def scale (c : Int) (x : Gaussian) : Gaussian := (c * x.1, c * x.2)
def normSq (x : Gaussian) : Int := x.1 * x.1 + x.2 * x.2

def rows : List (Int × Int × Int) :=
  [(-60, 72, -35),
    (-55, 80, -21),
    (52, -85, -1),
    (49, -84, 21),
    (63, -61, 48),
    (52, -68, 52),
    (68, -51, 53),
    (39, -83, 40),
    (-41, 91, 5),
    (45, -58, 68),
    (59, -46, 66),
    (30, -95, 7),
    (32, -60, 73),
    (48, -83, -27),
    (49, -32, 81),
    (-21, 79, -57),
    (-44, 80, 41),
    (63, -29, 72),
    (36, -19, 91),
    (21, -23, 95),
    (14, -99, -4),
    (-33, 80, 51),
    (-73, 36, -59),
    (-48, 1, -88),
    (-19, 75, 64),
    (31, 21, 93),
    (59, -6, 80),
    (2, 93, -37),
    (5, 84, -55),
    (16, 70, 70),
    (45, 28, 85),
    (-24, -75, -61),
    (27, -43, -86),
    (34, 65, 68),
    (70, -7, 72),
    (-61, -18, -77),
    (45, 60, 67),
    (54, 42, 73),
    (20, 47, -86),
    (28, 96, 6),
    (76, -20, 62),
    (25, 86, -44),
    (28, 10, -96),
    (41, -51, -76),
    (44, 82, 37),
    (71, 16, 68),
    (66, 39, 64),
    (42, 91, 6),
    (61, 58, 54),
    (57, 72, 40),
    (42, 88, -22),
    (-53, -83, -15),
    (38, 59, -71),
    (42, 76, -50),
    (40, -7, -91),
    (41, 34, -84),
    (79, 5, 61),
    (77, 29, 57),
    (74, 46, 49),
    (68, 65, 33),
    (-55, -79, 27),
    (65, 75, 12),
    (61, 79, -11),
    (52, -56, -64),
    (50, -29, -82),
    (-55, -65, 53),
    (77, 54, 33),
    (-51, -4, 86),
    (75, 65, 15),
    (-54, -38, 75),
    (84, -11, 54),
    (71, 69, -10),
    (61, 49, -62),
    (66, 63, -41),
    (84, 37, 40),
    (86, 18, 48),
    (-72, -62, 31),
    (60, 14, -79),
    (81, 59, -3),
    (84, 53, 13),
    (79, 57, -20),
    (88, 41, 25),
    (90, 26, 36),
    (73, 45, -51),
    (69, 30, -66),
    (89, 4, 46),
    (91, 39, 13),
    (89, 45, -2),
    (61, -22, -76),
    (82, 42, -39),
    (86, 43, -27),
    (90, 41, -15),
    (71, 9, -70),
    (80, 29, -53),
    (95, 24, 20),
    (94, 12, 31),
    (69, -10, -71),
    (95, 30, -1),
    (78, 7, -62),
    (84, 17, -51),
    (90, 26, -36),
    (95, 27, -18),
    (92, -7, 38),
    (98, 19, 6),
    (66, -37, -65),
    (94, 16, -29),
    (98, 17, -12),
    (90, 8, -42),
    (99, 7, 14),
    (97, -1, 25),
    (-77, 20, 61),
    (100, 6, -1),
    (-85, 6, 52),
    (87, -27, 41),
    (66, -54, -53),
    (92, -19, 33),
    (99, 1, -15),
    (96, -2, -28),
    (92, -9, -39),
    (84, -22, -49),
    (-98, 12, -14),
    (76, -39, -52),
    (99, -12, 3),
    (99, -13, -9),
    (96, -17, -24),
    (95, -23, 20),
    (91, -27, -33),
    (85, -36, -39),
    (95, -27, -16),
    (69, -61, -39),
    (96, -28, -2),
    (86, -40, 32),
    (78, -51, -36),
    (94, -34, 8),
    (90, -39, 22),
    (89, -42, -17),
    (83, -52, -22),
    (88, -47, -7),
    (-73, 64, 24),
    (87, -49, 7),
    (84, -50, 22),
    (76, -63, -12),
    (82, -57, 10),
    (79, -62, -1)]

/-- Multiply an ascending coefficient list by `a + b*z`. -/
def mulLinear (a : Int) (b : Gaussian) (p : List Gaussian) : List Gaussian :=
  List.zipWith add ((p.map (scale a)) ++ [zero]) (zero :: p.map (mul b))

/-- Product and weighted endpoint polynomial, using the final-order weights. -/
def coefficientStep (n : Nat) (state : List Gaussian × List Gaussian)
    (row : (Int × Int × Int) × Nat) : List Gaussian × List Gaussian :=
  let a := row.1.1
  let b := (row.1.2.1, row.1.2.2)
  let weight : Int := (n : Int) - 1 - 2 * (row.2 : Int)
  (mulLinear a b state.1,
    List.zipWith add (mulLinear a b state.2)
      (state.1.map (mul (scale weight b))))

def coefficients : List Gaussian × List Gaussian :=
  rows.zipIdx.foldl (coefficientStep 144) ([(1, 0)], [])

def factorial : Nat → Nat
  | 0 => 1
  | n + 1 => (n + 1) * factorial n

def coefficientNorm (degree : Nat) (p : List Gaussian) : Int :=
  (p.zipIdx.map fun ck =>
    ((factorial ck.2 * factorial (degree - ck.2) : Nat) : Int) * normSq ck.1).sum

def computedP : Int := coefficientNorm 144 coefficients.1

def computedS : Int := coefficientNorm 142 (coefficients.2.take 143)

def expectedP : Int := 133678240032012707743341823506761537111390070639378925921169528089493990441983374531942708065983919533849579416400504077876793432116093328138905769259876664891009240873430688961941951637993850318470633426580331039188349271336664817712560264323794511627824625833122047978762887898638010693864123094257070180998235154110234932640934563961259441310792539159453396757009137044909821370675479701107755742220764878298101833517779237722959000105604189250200448302419674561581821654043644151351122051952949543947182998796533111193458306154652760192241178619186506682910315285966684165646978481181039816542461951152335689626359995521995625624680935134338831598816624625729320972871814954626056447910155529524648209418846471633548345344000000000000000000000000000000000000000000

def expectedS : Int := 1376947256712251988527177698496421832783993365319876688843607345214548644835359944258487135623099644280281994129571487988240187994619406497865166087623053161657377351239037033096522643562031212654113814860095789066933092894792871737810219567423916656760932098883132633868105690222267587879209667852183008903066040388799231855653865963226145264141678808440493760289983191817671140724919486663107265919625557046954084984389677468396424914424625055448542235362937766758637873717739832144148886628426721505768508549427863102833251095175279986416390403168726456754617783914880346446696648533341458622044716572868997966072028696973231703981212797812886373796055407211045988947836422702490210308411600335612148472652136936537814288302080000000000000000000000000000000000000000000

def gap : Int := expectedS - 10296 * expectedP

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
/-- The coefficient calculation reproduces both stored exact integers. -/
theorem exact_coefficients : computedP = expectedP ∧ computedS = expectedS := by
  decide +kernel

/-- The strict sign margin is an ordinary integer inequality. -/
theorem strict_margin : expectedS > 10300 * expectedP := by
  decide +kernel

/-- The integer certificate has strictly negative endpoint numerator. -/
theorem endpoint_numerator_negative : 10296 * expectedP - expectedS < 0 := by
  decide +kernel

/-- All 144 ordered rows are present. -/
theorem rows_length : rows.length = 144 := by
  decide +kernel

#print axioms exact_coefficients
#print axioms strict_margin
#print axioms endpoint_numerator_negative

end Bapat.Certificate


-- Source: Bapat/CoefficientAlgebra.lean
/-!
# Algebraic meaning of the certificate's coefficient operations

The polynomial semantics is proved for arbitrary coefficient lists, not only
for the known numerical answer. The concrete certificate is computed in integers.
-/

namespace Bapat.Certificate

noncomputable section

def toComplex (z : Gaussian) : ℂ := (z.1 : ℂ) + (z.2 : ℂ) * Complex.I

@[simp] theorem toComplex_zero : toComplex zero = 0 := by
  simp [toComplex, zero]

theorem toComplex_add (x y : Gaussian) : toComplex (add x y) = toComplex x + toComplex y := by
  simp [toComplex, add]
  ring

theorem toComplex_mul (x y : Gaussian) : toComplex (mul x y) = toComplex x * toComplex y := by
  apply Complex.ext <;>
    simp [toComplex, mul, Complex.mul_re, Complex.mul_im]

theorem toComplex_scale (a : ℤ) (x : Gaussian) :
    toComplex (scale a x) = (a : ℂ) * toComplex x := by
  simp [toComplex, scale]
  ring

/-- Interpret an ascending coefficient list as a complex polynomial. -/
def asPolynomial : List Gaussian → Polynomial ℂ
  | [] => 0
  | c :: cs => Polynomial.C (toComplex c) + Polynomial.X * asPolynomial cs

theorem asPolynomial_append_zero (xs : List Gaussian) :
    asPolynomial (xs ++ [zero]) = asPolynomial xs := by
  induction xs with
  | nil => simp [asPolynomial]
  | cons x xs ih => simp [asPolynomial, ih]

theorem asPolynomial_zero_cons (xs : List Gaussian) :
    asPolynomial (zero :: xs) = Polynomial.X * asPolynomial xs := by
  simp [asPolynomial]

/-- Every polynomial coefficient is the corresponding Gaussian-integer list entry. -/
theorem asPolynomial_coeff (xs : List Gaussian) (k : ℕ) :
    (asPolynomial xs).coeff k = toComplex (xs.getD k zero) := by
  induction xs generalizing k with
  | nil => simp [asPolynomial, List.getD]
  | cons c cs ih =>
    cases k with
    | zero => simp [asPolynomial, List.getD]
    | succ k => simp [asPolynomial, List.getD, Polynomial.coeff_X_mul, ih]

theorem asPolynomial_map_scale (a : ℤ) (xs : List Gaussian) :
    asPolynomial (xs.map (scale a)) = Polynomial.C (a : ℂ) * asPolynomial xs := by
  induction xs with
  | nil => simp [asPolynomial]
  | cons x xs ih =>
    simp [asPolynomial, toComplex_scale, Polynomial.C_mul, ih]
    ring

theorem asPolynomial_map_mul (b : Gaussian) (xs : List Gaussian) :
    asPolynomial (xs.map (mul b)) = Polynomial.C (toComplex b) * asPolynomial xs := by
  induction xs with
  | nil => simp [asPolynomial]
  | cons x xs ih =>
    simp [asPolynomial, toComplex_mul, Polynomial.C_mul, ih]
    ring

theorem asPolynomial_zipWith_add (xs ys : List Gaussian) (hlen : xs.length = ys.length) :
    asPolynomial (List.zipWith add xs ys) = asPolynomial xs + asPolynomial ys := by
  induction xs generalizing ys with
  | nil =>
    have : ys = [] := List.length_eq_zero_iff.mp hlen.symm
    simp [this, asPolynomial]
  | cons x xs ih =>
    cases ys with
    | nil => simp at hlen
    | cons y ys =>
      have ht : xs.length = ys.length := Nat.succ.inj hlen
      simp [asPolynomial, toComplex_add, Polynomial.C_add, ih ys ht]
      ring

/-- The fast list update really multiplies by the intended linear factor. -/
theorem asPolynomial_mulLinear (a : ℤ) (b : Gaussian) (xs : List Gaussian) :
    asPolynomial (mulLinear a b xs) =
      (Polynomial.C (a : ℂ) + Polynomial.C (toComplex b) * Polynomial.X) * asPolynomial xs := by
  unfold mulLinear
  rw [asPolynomial_zipWith_add _ _ (by simp)]
  rw [asPolynomial_append_zero, asPolynomial_map_scale,
    asPolynomial_zero_cons, asPolynomial_map_mul]
  ring

/-- The companion update has the weighted-product recurrence in polynomial form. -/
theorem asPolynomial_weighted_update (a d : ℤ) (b : Gaussian)
    (p g : List Gaussian) (hlen : p.length = g.length + 1) :
    asPolynomial (List.zipWith add (mulLinear a b g) (p.map (mul (scale d b)))) =
      (Polynomial.C (a : ℂ) + Polynomial.C (toComplex b) * Polynomial.X) * asPolynomial g +
        Polynomial.C ((d : ℂ) * toComplex b) * asPolynomial p := by
  rw [asPolynomial_zipWith_add _ _ (by simp [mulLinear, hlen])]
  rw [asPolynomial_mulLinear, asPolynomial_map_mul, toComplex_scale]

#print axioms asPolynomial_mulLinear
#print axioms asPolynomial_weighted_update

end
end Bapat.Certificate


-- Source: Bapat/Shape.lean
/-! # The exact coefficient-list shape, including the cancelled leading term -/

namespace Bapat.Certificate

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
theorem coefficient_shape :
    coefficients.1.length = 145 ∧ coefficients.2.length = 144 ∧
      coefficients.2.drop 143 = [zero] := by
  decide +kernel

#print axioms coefficient_shape

end Bapat.Certificate


-- Source: Bapat/PolynomialCertificate.lean
/-!
# The complete coefficient recurrence represents the intended polynomials

This connects the integer computation to a product polynomial and its weighted
product-rule companion, for arbitrary lists of indexed rows. It does not assert
the remaining permanent / endpoint derivative identity.
-/

namespace Bapat.Certificate

noncomputable section

abbrev IndexedRow := (ℤ × ℤ × ℤ) × ℕ

def linearFactor (r : IndexedRow) : Polynomial ℂ :=
  Polynomial.C (r.1.1 : ℂ) +
    Polynomial.C (toComplex (r.1.2.1, r.1.2.2)) * Polynomial.X

def markedFactor (n : ℕ) (r : IndexedRow) : Polynomial ℂ :=
  Polynomial.C (((n : ℤ) - 1 - 2 * (r.2 : ℤ) : ℤ) : ℂ) *
    Polynomial.C (toComplex (r.1.2.1, r.1.2.2))

def productPolynomial (rs : List IndexedRow) : Polynomial ℂ :=
  (rs.map linearFactor).prod

def weightedPolynomial (n : ℕ) : List IndexedRow → Polynomial ℂ
  | [] => 0
  | r :: rs => linearFactor r * weightedPolynomial n rs +
      markedFactor n r * productPolynomial rs

theorem mulLinear_length (a : ℤ) (b : Gaussian) (xs : List Gaussian) :
    (mulLinear a b xs).length = xs.length + 1 := by
  simp [mulLinear]

theorem coefficientStep_length (n : ℕ) (st : List Gaussian × List Gaussian)
    (r : IndexedRow) (hlen : st.1.length = st.2.length + 1) :
    (coefficientStep n st r).1.length = (coefficientStep n st r).2.length + 1 := by
  simp [coefficientStep, mulLinear_length, hlen]

theorem coefficientStep_polynomials (n : ℕ) (st : List Gaussian × List Gaussian)
    (r : IndexedRow) (hlen : st.1.length = st.2.length + 1) :
    asPolynomial (coefficientStep n st r).1 = linearFactor r * asPolynomial st.1 ∧
    asPolynomial (coefficientStep n st r).2 =
      linearFactor r * asPolynomial st.2 + markedFactor n r * asPolynomial st.1 := by
  constructor
  · exact asPolynomial_mulLinear _ _ _
  · simpa [coefficientStep, linearFactor, markedFactor, Polynomial.C_mul] using
      asPolynomial_weighted_update r.1.1 ((n : ℤ) - 1 - 2 * (r.2 : ℤ))
        (r.1.2.1, r.1.2.2) st.1 st.2 hlen

/-- A full fold has the ordinary product and weighted product-rule semantics. -/
theorem foldl_polynomials (n : ℕ) (rs : List IndexedRow)
    (st : List Gaussian × List Gaussian) (hlen : st.1.length = st.2.length + 1) :
    asPolynomial (rs.foldl (coefficientStep n) st).1 =
      productPolynomial rs * asPolynomial st.1 ∧
    asPolynomial (rs.foldl (coefficientStep n) st).2 =
      productPolynomial rs * asPolynomial st.2 +
        weightedPolynomial n rs * asPolynomial st.1 := by
  induction rs generalizing st with
  | nil => simp [productPolynomial, weightedPolynomial]
  | cons r rs ih =>
    obtain ⟨hp, hg⟩ := ih (coefficientStep n st r) (coefficientStep_length n st r hlen)
    obtain ⟨hsp, hsg⟩ := coefficientStep_polynomials n st r hlen
    constructor
    · simp only [List.foldl_cons]
      rw [hp, hsp]
      simp only [productPolynomial, List.map_cons, List.prod_cons]
      ring
    · simp only [List.foldl_cons]
      rw [hg, hsp, hsg]
      simp only [productPolynomial, List.map_cons, List.prod_cons, weightedPolynomial]
      ring

/-- The particular kernel-checked lists are the intended degree-144 polynomials. -/
theorem certificate_polynomials :
    asPolynomial coefficients.1 = productPolynomial rows.zipIdx ∧
    asPolynomial coefficients.2 = weightedPolynomial 144 rows.zipIdx := by
  simpa [coefficients, asPolynomial, toComplex] using
    foldl_polynomials 144 rows.zipIdx ([(1, 0)], []) (by decide)

/-- Gaussian integer norm-squares agree with their complex interpretation. -/
theorem toComplex_normSq (z : Gaussian) : Complex.normSq (toComplex z) = (normSq z : ℝ) := by
  simp [Complex.normSq_apply, toComplex, normSq]

theorem factorial_eq (k : ℕ) : factorial k = Nat.factorial k := by
  induction k with
  | zero => rfl
  | succ k ih => simp [factorial, Nat.factorial_succ, ih]

/-- The discarded degree-143 coefficient is exactly zero, not an approximation. -/
theorem certificate_weighted_truncation :
    asPolynomial (coefficients.2.take 143) = weightedPolynomial 144 rows.zipIdx := by
  have hdrop := coefficient_shape.2.2
  have happ : coefficients.2.take 143 ++ [zero] = coefficients.2 := by
    rw [← hdrop]
    exact List.take_append_drop 143 coefficients.2
  calc
    asPolynomial (coefficients.2.take 143) =
        asPolynomial (coefficients.2.take 143 ++ [zero]) :=
      (asPolynomial_append_zero _).symm
    _ = asPolynomial coefficients.2 := congrArg asPolynomial happ
    _ = weightedPolynomial 144 rows.zipIdx := certificate_polynomials.2

#print axioms certificate_polynomials

end
end Bapat.Certificate


-- Source: Bapat/NormCertificate.lean
/-!
# The integer values are the factorial-weighted polynomial coefficient norms

Only their connection to the permutation derivative remains outside this module.
-/

open scoped BigOperators

namespace Bapat.Certificate

noncomputable section

def polynomialNorm (degree : ℕ) (p : Polynomial ℂ) : ℝ :=
  ∑ k : Fin (degree + 1),
    ((Nat.factorial k.val * Nat.factorial (degree - k.val) : ℕ) : ℝ) *
      Complex.normSq (p.coeff k.val)

theorem coefficientNorm_eq_sum (degree : ℕ) (xs : List Gaussian) :
    (coefficientNorm degree xs : ℝ) =
      ∑ k : Fin xs.length,
        ((Nat.factorial k.val * Nat.factorial (degree - k.val) : ℕ) : ℝ) *
          Complex.normSq ((asPolynomial xs).coeff k.val) := by
  have hm : (xs.zipIdx.map fun ck =>
      ((factorial ck.2 * factorial (degree - ck.2) : ℕ) : ℤ) * normSq ck.1) =
      xs.mapIdx (fun k c => ((factorial k * factorial (degree - k) : ℕ) : ℤ) * normSq c) := by
    rw [List.mapIdx_eq_zipIdx_map]
  rw [coefficientNorm, hm, List.mapIdx_eq_ofFn, List.sum_ofFn]
  push_cast
  apply Finset.sum_congr rfl
  intro k _
  rw [asPolynomial_coeff, toComplex_normSq, ← List.getElem_eq_getD (h := k.isLt) zero]
  simp [List.get_eq_getElem, factorial_eq]

theorem coefficientNorm_eq_polynomialNorm (degree : ℕ) (xs : List Gaussian)
    (hlen : xs.length = degree + 1) :
    (coefficientNorm degree xs : ℝ) = polynomialNorm degree (asPolynomial xs) := by
  have hsum := coefficientNorm_eq_sum degree xs
  rw [hlen] at hsum
  exact hsum

theorem expectedP_eq_polynomialNorm :
    (expectedP : ℝ) = polynomialNorm 144 (productPolynomial rows.zipIdx) := by
  rw [← exact_coefficients.1]
  change (coefficientNorm 144 coefficients.1 : ℝ) = _
  rw [coefficientNorm_eq_polynomialNorm 144 coefficients.1 coefficient_shape.1,
    certificate_polynomials.1]

theorem expectedS_eq_polynomialNorm :
    (expectedS : ℝ) = polynomialNorm 142 (weightedPolynomial 144 rows.zipIdx) := by
  rw [← exact_coefficients.2]
  change (coefficientNorm 142 (coefficients.2.take 143) : ℝ) = _
  rw [coefficientNorm_eq_polynomialNorm 142 (coefficients.2.take 143)
    (by simp [coefficient_shape.2.1]), certificate_weighted_truncation]

#print axioms expectedP_eq_polynomialNorm
#print axioms expectedS_eq_polynomialNorm

end
end Bapat.Certificate


-- Source: Bapat/WedgePolynomial.lean
/-!
# A product-rule shortcut for the ordered wedge polynomial

The pairwise 2-by-2 determinants can be aggregated recursively. Their sum is
minus the weighted polynomial g. The proof uses a product derivative and list
induction, avoiding a quadratic reindexing of products with two erased indices.
-/

namespace Bapat.Certificate

noncomputable section

abbrev Row := ℤ × ℤ × ℤ

def rowA (r : Row) : ℂ := r.1
def rowB (r : Row) : ℂ := toComplex (r.2.1, r.2.2)
def rowLinear (r : Row) : Polynomial ℂ := Polynomial.C (rowA r) +
  Polynomial.C (rowB r) * Polynomial.X

def rowProduct (rs : List Row) : Polynomial ℂ := (rs.map rowLinear).prod

theorem rowProduct_cons (r : Row) (rs : List Row) :
    rowProduct (r :: rs) = rowLinear r * rowProduct rs := by simp [rowProduct]

theorem productPolynomial_zipIdx (rs : List Row) (start : ℕ) :
    productPolynomial (rs.zipIdx start) = rowProduct rs := by
  unfold productPolynomial rowProduct
  have hmap : (rs.zipIdx start).map linearFactor = rs.map rowLinear := by
    calc
      (rs.zipIdx start).map linearFactor =
          ((rs.zipIdx start).map Prod.fst).map rowLinear := by
        rw [List.map_map]
        rfl
      _ = rs.map rowLinear := by rw [List.zipIdx_map_fst]
  rw [hmap]

theorem rowLinear_derivative (r : Row) :
    (rowLinear r).derivative = Polynomial.C (rowB r) := by
  simp [rowLinear]

/-- The weighted product rule, with an arbitrary initial integer weight. -/
def weightedBy (weight : ℤ) : List Row → Polynomial ℂ
  | [] => 0
  | r :: rs => rowLinear r * weightedBy (weight - 2) rs +
      Polynomial.C (weight : ℂ) * Polynomial.C (rowB r) * rowProduct rs

theorem weightedBy_shift (w d : ℤ) (rs : List Row) :
    weightedBy (w + d) rs = weightedBy w rs +
      Polynomial.C (d : ℂ) * (rowProduct rs).derivative := by
  induction rs generalizing w with
  | nil => simp [weightedBy, rowProduct]
  | cons r rs ih =>
    have hw : w + d - 2 = (w - 2) + d := by ring
    simp only [weightedBy, rowProduct_cons, Polynomial.derivative_mul,
      rowLinear_derivative]
    rw [hw, ih]
    simp only [Int.cast_add, Polynomial.C_add]
    ring

theorem weightedPolynomial_zipIdx (n : ℕ) (rs : List Row) (start : ℕ) :
    weightedPolynomial n (rs.zipIdx start) =
      weightedBy ((n : ℤ) - 1 - 2 * (start : ℤ)) rs := by
  induction rs generalizing start with
  | nil => simp [weightedPolynomial, weightedBy]
  | cons r rs ih =>
    simp only [List.zipIdx_cons, weightedPolynomial, weightedBy]
    rw [ih, productPolynomial_zipIdx]
    have hw : (n : ℤ) - 1 - 2 * ((start + 1 : ℕ) : ℤ) =
        ((n : ℤ) - 1 - 2 * (start : ℤ)) - 2 := by push_cast; ring
    rw [hw]
    rfl

/-- Cross terms from a fixed first row, preserving the order of the remaining list. -/
def crossPolynomial (r : Row) : List Row → Polynomial ℂ
  | [] => 0
  | s :: rs => Polynomial.C (rowA r * rowB s - rowA s * rowB r) * rowProduct rs +
      rowLinear s * crossPolynomial r rs

/-- Aggregate every ordered row pair once, including its complementary product. -/
def wedgePolynomial : List Row → Polynomial ℂ
  | [] => 0
  | r :: rs => rowLinear r * wedgePolynomial rs + crossPolynomial r rs

theorem crossPolynomial_eq_derivative (r : Row) (rs : List Row) :
    crossPolynomial r rs = rowLinear r * (rowProduct rs).derivative -
      Polynomial.C (rs.length : ℂ) * Polynomial.C (rowB r) * rowProduct rs := by
  induction rs with
  | nil => simp [crossPolynomial, rowProduct]
  | cons s rs ih =>
    simp only [crossPolynomial, ih, rowProduct_cons, List.length_cons,
      Nat.cast_add, Nat.cast_one, Polynomial.derivative_mul, rowLinear_derivative,
      Polynomial.C_sub, Polynomial.C_mul, Polynomial.C_add, Polynomial.C_1]
    simp only [rowLinear]
    ring

theorem wedgePolynomial_eq_weightedBy (rs : List Row) :
    wedgePolynomial rs = -weightedBy ((rs.length : ℤ) - 1) rs := by
  induction rs with
  | nil => simp [wedgePolynomial, weightedBy]
  | cons r rs ih =>
    have hw : ((rs.length : ℤ) - 1) + (-1) = (rs.length : ℤ) - 2 := by ring
    have hshift := weightedBy_shift ((rs.length : ℤ) - 1) (-1) rs
    rw [hw] at hshift
    simp only [Int.cast_neg, Int.cast_one, Polynomial.C_neg, Polynomial.C_1,
      neg_one_mul, ← sub_eq_add_neg] at hshift
    simp only [wedgePolynomial, ih, crossPolynomial_eq_derivative,
      List.length_cons, Nat.cast_add, Nat.cast_one, add_sub_cancel_right, weightedBy]
    rw [hshift]
    norm_cast
    ring

/-- The manuscript's F = -g identity, now proved for the actual ordered data. -/
theorem certificate_wedgePolynomial :
    wedgePolynomial rows = -weightedPolynomial 144 rows.zipIdx := by
  rw [wedgePolynomial_eq_weightedBy, weightedPolynomial_zipIdx]
  apply congrArg (fun w : ℤ => -weightedBy w rows)
  rw [rows_length]
  norm_num

theorem certificate_wedgeNorm : polynomialNorm 142 (wedgePolynomial rows) = (expectedS : ℝ) := by
  rw [certificate_wedgePolynomial, expectedS_eq_polynomialNorm]
  simp [polynomialNorm, Polynomial.coeff_neg]

#print axioms certificate_wedgePolynomial
#print axioms certificate_wedgeNorm

end
end Bapat.Certificate


-- Source: Bapat/Witness.lean
/-!
# The explicit Hermitian witness and an endpoint reduction

All arithmetic and positive-semidefiniteness facts below are proved.
The final theorem in this module is an endpoint reduction. The required identity
is proved unconditionally in `Bapat.Counterexample`.
-/

open scoped BigOperators ComplexOrder

namespace Bapat

noncomputable section

def gramFactor : Matrix (Fin 144) (Fin 2) ℂ := fun i j =>
  let row := Certificate.rows.getD i.val (0, 0, 0)
  if j = 0 then (row.1 : ℂ) else
    (row.2.1 : ℂ) + (row.2.2 : ℂ) * Complex.I

def gramWitness : Matrix (Fin 144) (Fin 144) ℂ :=
  gramFactor * gramFactor.conjTranspose

theorem gramWitness_posSemidef : gramWitness.PosSemidef :=
  Matrix.posSemidef_self_mul_conjTranspose gramFactor

theorem gramWitness_zero_one : gramWitness 0 1 = 9795 - 1288 * Complex.I := by
  apply Complex.ext <;>
    norm_num [gramWitness, Matrix.mul_apply, Fin.sum_univ_two,
      Matrix.conjTranspose_apply, gramFactor, Certificate.rows, List.getD,
      Complex.mul_re, Complex.mul_im]

theorem gramWitness_off_diagonal :
    ∃ i j : Fin 144, i ≠ j ∧ gramWitness i j ≠ 0 := by
  refine ⟨0, 1, by decide, ?_⟩
  intro hzero
  have hreal := congrArg Complex.re hzero
  rw [gramWitness_zero_one] at hreal
  norm_num at hreal

def explicitPositiveWitness : Matrix (Fin 144) (Fin 144) ℂ :=
  (10 ^ 70 : ℝ) • gramWitness + 1

theorem explicitPositiveWitness_posDef : explicitPositiveWitness.PosDef := by
  apply Matrix.PosDef.posSemidef_add
  · exact gramWitness_posSemidef.smul (by norm_num)
  · exact Matrix.PosDef.one

/-- Once the rank-two identity is supplied, all remaining disproof steps are finished. -/
theorem not_bapatMonotonicity_of_endpoint_identity
    (hidentity : 2 * endpointDerivative gramWitness =
      10296 * (Certificate.expectedP : ℝ) - (Certificate.expectedS : ℝ)) :
    ¬ BapatMonotonicity := by
  have hnum : (10296 : ℝ) * (Certificate.expectedP : ℝ) -
      (Certificate.expectedS : ℝ) < 0 := by
    exact_mod_cast Certificate.endpoint_numerator_negative
  have hneg : endpointDerivative gramWitness < 0 := by linarith
  exact not_bapatMonotonicity_of_psd_endpoint_negative gramWitness
    gramWitness_posSemidef hneg gramWitness_off_diagonal

#print axioms gramWitness_posSemidef
#print axioms explicitPositiveWitness_posDef
#print axioms not_bapatMonotonicity_of_endpoint_identity

end
end Bapat


-- Source: Bapat/RankTwoReduction.lean
/-!
# Rank-two minors and a coefficient-norm reduction

The general endpoint identity, Hermitian reality, scalar arithmetic, positivity
and the analytic perturbation reduction are proved. The final theorem below
takes two coefficient-norm identities as explicit hypotheses. Both identities
are proved and supplied by the final integration in `Bapat.Counterexample`.
-/

open scoped BigOperators

namespace Bapat

noncomputable section

def rowWedge {n : ℕ} (V : Matrix (Fin n) (Fin 2) ℂ) (i j : Fin n) : ℂ :=
  V i 0 * V j 1 - V j 0 * V i 1

/-- The two-column Cauchy–Binet calculation needs only commutative ring algebra. -/
theorem rankTwoGram_minor {n : ℕ} (V : Matrix (Fin n) (Fin 2) ℂ)
    (i j k l : Fin n) :
    (V * V.conjTranspose) i k * (V * V.conjTranspose) j l -
      (V * V.conjTranspose) i l * (V * V.conjTranspose) j k =
        rowWedge V i j * star (rowWedge V k l) := by
  simp only [Matrix.mul_apply, Fin.sum_univ_two, Matrix.conjTranspose_apply,
    rowWedge, star_sub, star_mul]
  ring

theorem rankTwo_pairMinorContribution {n : ℕ} (V : Matrix (Fin n) (Fin 2) ℂ)
    (i j : Fin n) (σ : Equiv.Perm (Fin n)) :
    pairMinorContribution (V * V.conjTranspose) i j σ =
      if σ i < σ j then
        rowWedge V i j * star (rowWedge V (σ i) (σ j)) *
          remainingProduct (V * V.conjTranspose) σ i j
      else 0 := by
  unfold pairMinorContribution
  rw [rankTwoGram_minor]

/-- All remaining disproof work is isolated in two rank-two norm identities. -/
theorem not_bapatMonotonicity_of_rankTwo_norms
    (hper : gramWitness.permanent.re =
      Certificate.polynomialNorm 144 (Certificate.rowProduct Certificate.rows))
    (hminor : (pairMinorSum gramWitness).re =
      Certificate.polynomialNorm 142 (Certificate.wedgePolynomial Certificate.rows)) :
    ¬ BapatMonotonicity := by
  apply not_bapatMonotonicity_of_endpoint_identity
  have hid := endpointDerivative_pairMinorSum gramWitness
  rw [rowPairs_144_card, qPermanent_one, hper, hminor,
    Certificate.certificate_wedgeNorm,
    ← Certificate.productPolynomial_zipIdx Certificate.rows 0,
    ← Certificate.expectedP_eq_polynomialNorm] at hid
  exact hid

#print axioms rankTwoGram_minor
#print axioms not_bapatMonotonicity_of_rankTwo_norms

end
end Bapat


-- Source: Bapat/ComplementPermanent.lean
/-! # Complementary bijections, without enumeration of full permutations -/

open scoped BigOperators

namespace Bapat

noncomputable section

abbrev PairComplement {n : ℕ} (i j : Fin n) := {x : Fin n // x ≠ i ∧ x ≠ j}

def restrictPair {n : ℕ} {i j k l : Fin n} (σ : Equiv.Perm (Fin n))
    (hi : σ i = k) (hj : σ j = l) : PairComplement i j ≃ PairComplement k l where
  toFun x := ⟨σ x, by
    constructor
    · intro h; exact x.property.1 (σ.injective (h.trans hi.symm))
    · intro h; exact x.property.2 (σ.injective (h.trans hj.symm))⟩
  invFun y := ⟨σ.symm y, by
    constructor
    · intro h; exact y.property.1 (by simpa [h, hi] using (σ.apply_symm_apply y).symm)
    · intro h; exact y.property.2 (by simpa [h, hj] using (σ.apply_symm_apply y).symm)⟩
  left_inv x := by ext; simp
  right_inv y := by ext; simp

def extendPair {n : ℕ} {i j k l : Fin n} (hij : i ≠ j) (hkl : k ≠ l)
    (e : PairComplement i j ≃ PairComplement k l) : Equiv.Perm (Fin n) where
  toFun x := if hi : x = i then k else if hj : x = j then l else e ⟨x, hi, hj⟩
  invFun y := if hk : y = k then i else if hl : y = l then j else e.symm ⟨y, hk, hl⟩
  left_inv x := by
    by_cases hi : x = i
    · subst x; simp
    by_cases hj : x = j
    · subst x; simp [hij.symm, hkl.symm]
    · simp only [dite_eq_right hi, dite_eq_right hj]
      have h := (e ⟨x, hi, hj⟩).property
      simp only [dite_eq_right h.1, dite_eq_right h.2]
      change (e.symm (e ⟨x, hi, hj⟩)).val = x
      simp
  right_inv y := by
    by_cases hk : y = k
    · subst y; simp
    by_cases hl : y = l
    · subst y; simp [hij.symm, hkl.symm]
    · simp only [dite_eq_right hk, dite_eq_right hl]
      have h := (e.symm ⟨y, hk, hl⟩).property
      simp only [dite_eq_right h.1, dite_eq_right h.2]
      change (e (e.symm ⟨y, hk, hl⟩)).val = y
      simp

theorem extendPair_left {n : ℕ} {i j k l : Fin n} (hij : i ≠ j) (hkl : k ≠ l)
    (e : PairComplement i j ≃ PairComplement k l) : extendPair hij hkl e i = k := by
  simp [extendPair]

theorem extendPair_right {n : ℕ} {i j k l : Fin n} (hij : i ≠ j) (hkl : k ≠ l)
    (e : PairComplement i j ≃ PairComplement k l) : extendPair hij hkl e j = l := by
  simp [extendPair, hij.symm]

theorem extendPair_complement {n : ℕ} {i j k l : Fin n}
    (hij : i ≠ j) (hkl : k ≠ l) (e : PairComplement i j ≃ PairComplement k l)
    (x : PairComplement i j) : extendPair hij hkl e x = e x := by
  simp [extendPair, x.property.1, x.property.2]

def pairMatchingEquiv {n : ℕ} {i j k l : Fin n} (hij : i ≠ j) (hkl : k ≠ l) :
    {σ : Equiv.Perm (Fin n) // σ i = k ∧ σ j = l} ≃
      (PairComplement i j ≃ PairComplement k l) where
  toFun σ := restrictPair σ.val σ.property.1 σ.property.2
  invFun e := ⟨extendPair hij hkl e, extendPair_left hij hkl e, extendPair_right hij hkl e⟩
  left_inv σ := by
    apply Subtype.ext
    apply Equiv.ext
    intro x
    by_cases hi : x = i
    · subst x; simp [extendPair_left, σ.property.1]
    by_cases hj : x = j
    · subst x; simp [extendPair_right, σ.property.2]
    · change extendPair hij hkl (restrictPair σ.val σ.property.1 σ.property.2) x = σ.val x
      simp [extendPair, hi, hj, restrictPair]
  right_inv e := by
    apply Equiv.ext
    intro x
    apply Subtype.ext
    exact extendPair_complement hij hkl e x

theorem pairComplement_card {n : ℕ} (i j : Fin n) (hij : i ≠ j) :
    Fintype.card (PairComplement i j) = n - 2 := by
  classical
  rw [Fintype.card_subtype]
  have hset : (Finset.univ.filter fun x : Fin n => x ≠ i ∧ x ≠ j) =
      (Finset.univ.erase i).erase j := by ext; simp [and_comm]
  rw [hset, Finset.card_erase_of_mem (by simp [hij.symm]),
    Finset.card_erase_of_mem (Finset.mem_univ i), Finset.card_univ, Fintype.card_fin]
  omega

def pairComplementFin {n : ℕ} (i j : Fin n) (hij : i ≠ j) :
    PairComplement i j ≃ Fin (n - 2) :=
  Fintype.equivFinOfCardEq (pairComplement_card i j hij)

def pairMatchingFinEquiv {n : ℕ} {i j k l : Fin n} (hij : i ≠ j) (hkl : k ≠ l) :
    {σ : Equiv.Perm (Fin n) // σ i = k ∧ σ j = l} ≃ Equiv.Perm (Fin (n - 2)) :=
  (pairMatchingEquiv hij hkl).trans
    (Equiv.equivCongr (pairComplementFin i j hij) (pairComplementFin k l hkl))

theorem remainingProduct_subtype {n : ℕ} (A : Matrix (Fin n) (Fin n) ℂ)
    (σ : Equiv.Perm (Fin n)) (i j : Fin n) :
    remainingProduct A σ i j = ∏ x : PairComplement i j, A x (σ x) := by
  classical
  unfold remainingProduct
  exact Finset.prod_subtype _ (by intro x; simp [and_comm]) _

def complementMatrix {n : ℕ} (V : Matrix (Fin n) (Fin 2) ℂ)
    (i j : Fin n) (hij : i ≠ j) : Matrix (Fin (n - 2)) (Fin 2) ℂ :=
  fun a c => V ((pairComplementFin i j hij).symm a) c

def complementPolynomial {n : ℕ} (V : Matrix (Fin n) (Fin 2) ℂ)
    (i j : Fin n) : Polynomial ℂ :=
  ∏ x ∈ (Finset.univ.erase i).erase j,
    (Polynomial.C (V x 0) + Polynomial.C (V x 1) * Polynomial.X)

theorem factorPolynomial_complementMatrix {n : ℕ} (V : Matrix (Fin n) (Fin 2) ℂ)
    (i j : Fin n) (hij : i ≠ j) :
    factorPolynomial (complementMatrix V i j hij) = complementPolynomial V i j := by
  classical
  unfold factorPolynomial complementPolynomial complementMatrix
  rw [Finset.prod_subtype (p := fun x : Fin n => x ≠ i ∧ x ≠ j)
    ((Finset.univ.erase i).erase j) (by intro x; simp [and_comm])]
  exact Fintype.prod_equiv (pairComplementFin i j hij).symm _ _ (by intro x; rfl)

theorem remainingGram_matching_sum {n : ℕ} (U W : Matrix (Fin n) (Fin 2) ℂ)
    (i j k l : Fin n) (hij : i ≠ j) (hkl : k ≠ l) :
    (∑ σ : Equiv.Perm (Fin n), if σ i = k ∧ σ j = l then
      remainingProduct (U * W.conjTranspose) σ i j else 0) =
    (complementMatrix U i j hij * (complementMatrix W k l hkl).conjTranspose).permanent := by
  classical
  rw [← Finset.sum_filter,
    Finset.sum_subtype (p := fun σ : Equiv.Perm (Fin n) => σ i = k ∧ σ j = l)
      _ (by intro σ; simp)]
  rw [← Matrix.permanent_transpose]
  unfold Matrix.permanent
  apply Fintype.sum_equiv (pairMatchingFinEquiv hij hkl)
  intro σ
  rw [remainingProduct_subtype]
  apply Fintype.prod_equiv (pairComplementFin i j hij)
  intro x
  simp [Matrix.transpose_apply, Matrix.mul_apply, Matrix.conjTranspose_apply,
    complementMatrix, pairMatchingFinEquiv, pairMatchingEquiv,
    pairComplementFin, Equiv.equivCongr, restrictPair]

theorem remainingGram_matching_coefficients {n : ℕ}
    (U W : Matrix (Fin n) (Fin 2) ℂ) (i j k l : Fin n)
    (hij : i ≠ j) (hkl : k ≠ l) :
    (∑ σ : Equiv.Perm (Fin n), if σ i = k ∧ σ j = l then
      remainingProduct (U * W.conjTranspose) σ i j else 0) =
      ∑ d : Fin (n - 2 + 1), ((d.val.factorial * (n - 2 - d.val).factorial : ℕ) : ℂ) *
        (complementPolynomial U i j).coeff d.val *
          star ((complementPolynomial W k l).coeff d.val) := by
  rw [remainingGram_matching_sum U W i j k l hij hkl, gram_permanent_coefficients,
    factorPolynomial_complementMatrix, factorPolynomial_complementMatrix]

#print axioms pairMatchingFinEquiv
#print axioms remainingGram_matching_coefficients

theorem imagePair_sum {n : ℕ} (V : Matrix (Fin n) (Fin 2) ℂ)
    (σ : Equiv.Perm (Fin n)) (i j : Fin n) :
    (∑ q ∈ rowPairs n, if σ i = q.1 ∧ σ j = q.2 then
      star (rowWedge V q.1 q.2) * remainingProduct (V * V.conjTranspose) σ i j else 0) =
      if σ i < σ j then
        star (rowWedge V (σ i) (σ j)) * remainingProduct (V * V.conjTranspose) σ i j
      else 0 := by
  classical
  by_cases h : σ i < σ j
  · rw [ite_eq_left h]
    refine (Finset.sum_eq_single (σ i, σ j) ?_ ?_).trans ?_
    · intro q _ hq
      have hm : ¬ (σ i = q.1 ∧ σ j = q.2) := by
        intro hm; exact hq (Prod.ext hm.1.symm hm.2.symm)
      simp [hm]
    · intro hm; exact (hm (by simp [rowPairs, h])).elim
    · simp
  · rw [ite_eq_right h]
    apply Finset.sum_eq_zero
    intro q hq
    have hm : ¬ (σ i = q.1 ∧ σ j = q.2) := by
      intro hm
      exact h (by simpa [hm.1, hm.2] using (Finset.mem_filter.mp hq).2)
    simp [hm]

theorem pairMinorGram_pairs {n : ℕ} (V : Matrix (Fin n) (Fin 2) ℂ) :
    pairMinorSum (V * V.conjTranspose) =
      ∑ p ∈ rowPairs n, rowWedge V p.1 p.2 *
        ∑ q ∈ rowPairs n, star (rowWedge V q.1 q.2) *
          ∑ σ : Equiv.Perm (Fin n), if σ p.1 = q.1 ∧ σ p.2 = q.2 then
            remainingProduct (V * V.conjTranspose) σ p.1 p.2 else 0 := by
  classical
  unfold pairMinorSum
  apply Finset.sum_congr rfl
  intro p _
  simp_rw [rankTwo_pairMinorContribution]
  have hfactor : ∀ σ : Equiv.Perm (Fin n),
      (if σ p.1 < σ p.2 then rowWedge V p.1 p.2 *
        star (rowWedge V (σ p.1) (σ p.2)) *
          remainingProduct (V * V.conjTranspose) σ p.1 p.2 else 0) =
      rowWedge V p.1 p.2 * (if σ p.1 < σ p.2 then
        star (rowWedge V (σ p.1) (σ p.2)) *
          remainingProduct (V * V.conjTranspose) σ p.1 p.2 else 0) := by
    intro σ; split_ifs <;> ring
  simp_rw [hfactor]
  rw [← Finset.mul_sum]
  congr 1
  simp_rw [← imagePair_sum V]
  rw [Finset.sum_comm]
  apply Finset.sum_congr rfl
  intro q _
  rw [Finset.mul_sum]
  apply Finset.sum_congr rfl
  intro σ _
  split_ifs <;> simp

def pairPolynomial {n : ℕ} (V : Matrix (Fin n) (Fin 2) ℂ) : Polynomial ℂ :=
  ∑ p ∈ rowPairs n, Polynomial.C (rowWedge V p.1 p.2) * complementPolynomial V p.1 p.2

theorem pairPolynomial_coeff {n : ℕ} (V : Matrix (Fin n) (Fin 2) ℂ) (d : ℕ) :
    (pairPolynomial V).coeff d = ∑ p ∈ rowPairs n,
      rowWedge V p.1 p.2 * (complementPolynomial V p.1 p.2).coeff d := by
  classical
  simp [pairPolynomial, Polynomial.finsetSum_coeff]

theorem pairMinorGram_coefficients {n : ℕ} (V : Matrix (Fin n) (Fin 2) ℂ) :
    pairMinorSum (V * V.conjTranspose) =
      ∑ d : Fin (n - 2 + 1), ((d.val.factorial * (n - 2 - d.val).factorial : ℕ) : ℂ) *
        (pairPolynomial V).coeff d.val * star ((pairPolynomial V).coeff d.val) := by
  classical
  have hexpand : pairMinorSum (V * V.conjTranspose) =
      ∑ p ∈ rowPairs n, ∑ q ∈ rowPairs n, ∑ d : Fin (n - 2 + 1),
        ((d.val.factorial * (n - 2 - d.val).factorial : ℕ) : ℂ) *
          (rowWedge V p.1 p.2 * (complementPolynomial V p.1 p.2).coeff d.val) *
            star (rowWedge V q.1 q.2 * (complementPolynomial V q.1 q.2).coeff d.val) := by
    rw [pairMinorGram_pairs]
    apply Finset.sum_congr rfl
    intro p hp
    rw [Finset.mul_sum]
    apply Finset.sum_congr rfl
    intro q hq
    rw [remainingGram_matching_coefficients V V p.1 p.2 q.1 q.2
      (Finset.mem_filter.mp hp).2.ne (Finset.mem_filter.mp hq).2.ne]
    simp_rw [Finset.mul_sum]
    apply Finset.sum_congr rfl
    intro d _
    rw [star_mul]
    ring
  rw [hexpand]
  conv_lhs => arg 2; ext p; rw [Finset.sum_comm]
  rw [Finset.sum_comm]
  simp_rw [pairPolynomial_coeff, star_sum, Finset.mul_sum, Finset.sum_mul]
  apply Finset.sum_congr rfl
  intro d _
  exact Finset.sum_comm

theorem pairMinorGram_norm {n : ℕ} (V : Matrix (Fin n) (Fin 2) ℂ) :
    (pairMinorSum (V * V.conjTranspose)).re =
      Certificate.polynomialNorm (n - 2) (pairPolynomial V) := by
  rw [pairMinorGram_coefficients]
  simp_rw [mul_assoc, Complex.star_def, Complex.mul_conj]
  simp [Certificate.polynomialNorm]

#print axioms pairMinorGram_norm

end
end Bapat


-- Source: Bapat/PairPolynomial.lean
/-! # Ordered row pairs reduce to the weighted product rule -/

open scoped BigOperators

namespace Bapat

noncomputable section

set_option maxRecDepth 10000

def deletedFactorPolynomial {n : ℕ} (V : Matrix (Fin n) (Fin 2) ℂ)
    (i : Fin n) : Polynomial ℂ :=
  ∏ x ∈ Finset.univ.erase i,
    (Polynomial.C (V x 0) + Polynomial.C (V x 1) * Polynomial.X)

theorem deletedFactorPolynomial_ite {n : ℕ} (V : Matrix (Fin n) (Fin 2) ℂ)
    (i : Fin n) : deletedFactorPolynomial V i =
      ∏ x, if x = i then 1 else
        (Polynomial.C (V x 0) + Polynomial.C (V x 1) * Polynomial.X) := by
  classical
  unfold deletedFactorPolynomial
  simp only [Finset.prod_ite, Finset.prod_const_one, one_mul]
  have hs : (Finset.univ.filter fun x : Fin n => ¬x = i) = Finset.univ.erase i := by
    ext x; simp
  rw [hs]

theorem pairPolynomial_term {n : ℕ} (V : Matrix (Fin n) (Fin 2) ℂ)
    (i j : Fin n) (hij : i ≠ j) :
    Polynomial.C (rowWedge V i j) * complementPolynomial V i j =
      Polynomial.C (V j 1) * deletedFactorPolynomial V j -
        Polynomial.C (V i 1) * deletedFactorPolynomial V i := by
  classical
  unfold deletedFactorPolynomial
  rw [← Finset.mul_prod_erase _ _ (show i ∈ (Finset.univ : Finset (Fin n)).erase j by
    simp [hij]),
    ← Finset.mul_prod_erase _ _ (show j ∈ (Finset.univ : Finset (Fin n)).erase i by
    simp [hij.symm])]
  have hs : ((Finset.univ : Finset (Fin n)).erase j).erase i =
      (Finset.univ.erase i).erase j := by ext x; simp [and_comm]
  rw [hs]
  simp only [rowWedge, Polynomial.C_sub, Polynomial.C_mul, complementPolynomial]
  ring

theorem ordered_pair_differences {n : ℕ} (T : Fin n → Polynomial ℂ) :
    (∑ p ∈ rowPairs n, (T p.2 - T p.1)) =
      ∑ i, Polynomial.C (2 * (i.val : ℂ) + 1 - (n : ℂ)) * T i := by
  classical
  unfold rowPairs
  rw [Finset.sum_filter]
  have hit : ∀ i j : Fin n, (if i < j then T j - T i else 0) =
      (if i < j then T j else 0) - (if i < j then T i else 0) := by
    intro i j; split_ifs <;> simp
  simp_rw [hit]
  rw [Finset.sum_sub_distrib]
  simp_rw [Fintype.sum_prod_type]
  conv_lhs => arg 1; rw [Finset.sum_comm]
  have hlo : ∀ j : Fin n, (∑ i : Fin n, if i < j then T j else 0) = j.val • T j := by
    intro j
    rw [← Finset.sum_filter]
    have hs : (Finset.univ.filter fun i : Fin n => i < j) = Finset.Iio j := by ext; simp
    rw [hs, Finset.sum_const, Fin.card_Iio]
  have hhi : ∀ i : Fin n, (∑ j : Fin n, if i < j then T i else 0) =
      (n - 1 - i.val) • T i := by
    intro i
    rw [← Finset.sum_filter]
    have hs : (Finset.univ.filter fun j : Fin n => i < j) = Finset.Ioi i := by ext; simp
    rw [hs, Finset.sum_const, Fin.card_Ioi]
  simp_rw [hlo, hhi]
  rw [← Finset.sum_sub_distrib]
  apply Finset.sum_congr rfl
  intro i _
  have hi_lt := i.isLt
  have hc : ((n - 1 - i.val : ℕ) : ℂ) = (n : ℂ) - 1 - (i.val : ℂ) := by
    have hn : 1 ≤ n := by omega
    have hi : i.val ≤ n - 1 := by omega
    rw [Nat.cast_sub hi, Nat.cast_sub hn, Nat.cast_one]
  simp only [nsmul_eq_mul, ← Polynomial.C_eq_natCast]
  rw [hc, ← sub_mul, ← Polynomial.C_sub]
  congr 2
  ring

theorem pairPolynomial_weighted {n : ℕ} (V : Matrix (Fin n) (Fin 2) ℂ) :
    pairPolynomial V = ∑ i,
      Polynomial.C (2 * (i.val : ℂ) + 1 - (n : ℂ)) *
        (Polynomial.C (V i 1) * deletedFactorPolynomial V i) := by
  classical
  unfold pairPolynomial
  have ht : ∀ p ∈ rowPairs n,
      Polynomial.C (rowWedge V p.1 p.2) * complementPolynomial V p.1 p.2 =
        Polynomial.C (V p.2 1) * deletedFactorPolynomial V p.2 -
          Polynomial.C (V p.1 1) * deletedFactorPolynomial V p.1 := by
    intro p hp
    exact pairPolynomial_term V p.1 p.2 (Finset.mem_filter.mp hp).2.ne
  rw [Finset.sum_congr rfl ht]
  exact ordered_pair_differences (fun i => Polynomial.C (V i 1) * deletedFactorPolynomial V i)

namespace Certificate

def deletedListProduct (rs : List Row) (i : Fin rs.length) : Polynomial ℂ :=
  ∏ j : Fin rs.length, if j = i then 1 else rowLinear rs[j.val]

theorem deletedListProduct_cons_zero (r : Row) (rs : List Row) :
    deletedListProduct (r :: rs) 0 = rowProduct rs := by
  simp [deletedListProduct, Fin.prod_univ_succ, rowProduct,
    Fin.prod_univ_fun_getElem]

theorem deletedListProduct_cons_succ (r : Row) (rs : List Row) (i : Fin rs.length) :
    deletedListProduct (r :: rs) i.succ = rowLinear r * deletedListProduct rs i := by
  have hn : (0 : Fin (rs.length + 1)) ≠ i.succ := (Fin.succ_ne_zero i).symm
  simp [deletedListProduct, Fin.prod_univ_succ, hn]

theorem weightedBy_expansion (w : ℤ) (rs : List Row) :
    weightedBy w rs = ∑ i : Fin rs.length,
      Polynomial.C ((w - 2 * (i.val : ℤ) : ℤ) : ℂ) *
        Polynomial.C (rowB rs[i.val]) * deletedListProduct rs i := by
  induction rs generalizing w with
  | nil => simp [weightedBy]
  | cons r rs ih =>
    rw [weightedBy]
    change _ = ∑ i : Fin (rs.length + 1),
      Polynomial.C ((w - 2 * (i.val : ℤ) : ℤ) : ℂ) *
        Polynomial.C (rowB (r :: rs)[i.val]) * deletedListProduct (r :: rs) i
    rw [Fin.sum_univ_succ]
    simp only [Fin.val_zero, Nat.cast_zero, mul_zero, sub_zero,
      List.getElem_cons_zero, deletedListProduct_cons_zero,
      List.getElem_cons_succ, Fin.val_succ, deletedListProduct_cons_succ]
    rw [ih, Finset.mul_sum, add_comm]
    apply congrArg (fun z : Polynomial ℂ =>
      Polynomial.C (w : ℂ) * Polynomial.C (rowB r) * rowProduct rs + z)
    apply Finset.sum_congr rfl
    intro i _
    have hw : (w - 2) - 2 * (i.val : ℤ) = w - 2 * ((i.val + 1 : ℕ) : ℤ) := by
      push_cast; ring
    rw [hw]
    ring

end Certificate

theorem gramFactor_rowA (i : Fin Certificate.rows.length) :
    gramFactor (finCongr Certificate.rows_length i) 0 =
      Certificate.rowA Certificate.rows[i.val] := by
  unfold gramFactor Certificate.rowA
  rw [List.getElem_eq_getD (0, 0, 0)]
  simp

theorem gramFactor_rowB (i : Fin Certificate.rows.length) :
    gramFactor (finCongr Certificate.rows_length i) 1 =
      Certificate.rowB Certificate.rows[i.val] := by
  unfold gramFactor Certificate.rowB
  rw [List.getElem_eq_getD (0, 0, 0)]
  simp [Certificate.toComplex]

theorem deletedListProduct_rows (i : Fin Certificate.rows.length) :
    Certificate.deletedListProduct Certificate.rows i =
      deletedFactorPolynomial gramFactor (finCongr Certificate.rows_length i) := by
  classical
  rw [deletedFactorPolynomial_ite]
  unfold Certificate.deletedListProduct
  apply Fintype.prod_equiv (finCongr Certificate.rows_length)
  intro j
  have he : finCongr Certificate.rows_length j = finCongr Certificate.rows_length i ↔ j = i :=
    (finCongr Certificate.rows_length).injective.eq_iff
  simp only [he, gramFactor_rowA, gramFactor_rowB, Certificate.rowLinear]

theorem weightedBy_rows_expansion : Certificate.weightedBy 143 Certificate.rows =
    ∑ i : Fin 144, Polynomial.C (((143 : ℤ) - 2 * (i.val : ℤ) : ℤ) : ℂ) *
      Polynomial.C (gramFactor i 1) * deletedFactorPolynomial gramFactor i := by
  rw [Certificate.weightedBy_expansion]
  apply Fintype.sum_equiv (finCongr Certificate.rows_length)
  intro i
  rw [gramFactor_rowB, deletedListProduct_rows]
  rfl

theorem pairPolynomial_gramFactor :
    pairPolynomial gramFactor = Certificate.wedgePolynomial Certificate.rows := by
  classical
  rw [Certificate.wedgePolynomial_eq_weightedBy, Certificate.rows_length]
  change pairPolynomial gramFactor = -Certificate.weightedBy 143 Certificate.rows
  rw [pairPolynomial_weighted, weightedBy_rows_expansion, ← Finset.sum_neg_distrib]
  apply Finset.sum_congr rfl
  intro i _
  simp only [Int.cast_sub, Int.cast_mul, Int.cast_ofNat, Int.cast_natCast,
    Nat.cast_ofNat, Polynomial.C_add, Polynomial.C_sub, Polynomial.C_mul,
    Polynomial.C_ofNat, Polynomial.C_1]
  ring

#print axioms pairPolynomial_gramFactor

#print axioms pairPolynomial_weighted
#print axioms Certificate.weightedBy_expansion

end
end Bapat


-- Source: Bapat/PermanentCertificate.lean
/-!
# The permanent coefficient identity for the exact 144-row witness

The permanent norm identity is unconditional. The reduction in this module
takes a complementary-minor identity, proved in `Bapat.Counterexample`.
-/

open scoped BigOperators

namespace Bapat

noncomputable section

theorem gram_permanent_norm {n : ℕ} (V : Matrix (Fin n) (Fin 2) ℂ) :
    (V * V.conjTranspose).permanent.re =
      Certificate.polynomialNorm n (factorPolynomial V) := by
  rw [gram_permanent_coefficients]
  simp_rw [mul_assoc, Complex.star_def, Complex.mul_conj]
  simp [Certificate.polynomialNorm]

theorem factorPolynomial_gramFactor :
    factorPolynomial gramFactor = Certificate.rowProduct Certificate.rows := by
  unfold factorPolynomial Certificate.rowProduct
  rw [← Fin.prod_univ_fun_getElem Certificate.rows Certificate.rowLinear]
  apply Fintype.prod_equiv (finCongr Certificate.rows_length.symm)
  intro i
  rw [List.getElem_eq_getD (0, 0, 0)]
  simp [gramFactor, Certificate.rowLinear, Certificate.rowA, Certificate.rowB,
    Certificate.toComplex]

theorem gramWitness_permanent : gramWitness.permanent.re = (Certificate.expectedP : ℝ) := by
  change (gramFactor * gramFactor.conjTranspose).permanent.re = _
  rw [gram_permanent_norm, factorPolynomial_gramFactor,
    ← Certificate.productPolynomial_zipIdx Certificate.rows 0,
    ← Certificate.expectedP_eq_polynomialNorm]

theorem gramWitness_permanent_exact : gramWitness.permanent = (Certificate.expectedP : ℂ) := by
  rw [← complexQPermanent_one,
    complexQPermanent_eq_real gramWitness gramWitness_posSemidef.1,
    qPermanent_one, gramWitness_permanent]
  norm_cast

/-- A scalar reduction used by the unconditional theorem in `Bapat.Counterexample`. -/
theorem not_bapatMonotonicity_of_minor_identity
    (hminor : (pairMinorSum gramWitness).re = (Certificate.expectedS : ℝ)) :
    ¬ BapatMonotonicity := by
  apply not_bapatMonotonicity_of_endpoint_identity
  have hid := endpointDerivative_pairMinorSum gramWitness
  rw [rowPairs_144_card, qPermanent_one, gramWitness_permanent, hminor] at hid
  exact hid

#print axioms gramWitness_permanent
#print axioms gramWitness_permanent_exact
#print axioms not_bapatMonotonicity_of_minor_identity

end
end Bapat


-- Source: Bapat/Counterexample.lean
/-!
# A formal disproof of the original Bapat–Lal monotonicity conjecture

The 144-row integer certificate yields a negative endpoint derivative for a
positive-semidefinite Gram matrix. A sufficiently small positive diagonal
perturbation is positive definite and still has a negative endpoint derivative.
No unproved identity or explicit quantitative perturbation bound is assumed.
-/

open scoped ComplexOrder

namespace Bapat

noncomputable section

theorem gramWitness_minorSum :
    (pairMinorSum gramWitness).re = (Certificate.expectedS : ℝ) := by
  change (pairMinorSum (gramFactor * gramFactor.conjTranspose)).re = _
  rw [pairMinorGram_norm, pairPolynomial_gramFactor]
  exact Certificate.certificate_wedgeNorm

theorem gramWitness_endpoint_identity :
    2 * endpointDerivative gramWitness =
      10296 * (Certificate.expectedP : ℝ) - (Certificate.expectedS : ℝ) := by
  have hid := endpointDerivative_pairMinorSum gramWitness
  rw [rowPairs_144_card, qPermanent_one, gramWitness_permanent, gramWitness_minorSum] at hid
  exact hid

theorem gramWitness_endpoint_negative : endpointDerivative gramWitness < 0 := by
  have hnum : (10296 : ℝ) * (Certificate.expectedP : ℝ) -
      (Certificate.expectedS : ℝ) < 0 := by
    exact_mod_cast Certificate.endpoint_numerator_negative
  have hid := gramWitness_endpoint_identity
  linarith

/-- A positive definite counterexample exists at the original dimension 144. -/
theorem exists_positive_definite_counterexample :
    ∃ ε : ℝ, 0 < ε ∧ (gramWitness + ε • 1).PosDef ∧
      ¬ (gramWitness + ε • 1).IsDiag ∧
      ¬ StrictMonoOn (qPermanent (gramWitness + ε • 1)) (Set.Icc (-1) 1) := by
  obtain ⟨ε, hε, hneg⟩ :=
    exists_positive_perturbation_negative gramWitness gramWitness_endpoint_negative
  refine ⟨ε, hε, positive_perturbation_posDef gramWitness gramWitness_posSemidef hε, ?_,
    not_strictMonoOn_of_endpoint_negative _ hneg⟩
  obtain ⟨i, j, hij, hval⟩ := gramWitness_off_diagonal
  intro hdiag
  have hzero := hdiag hij
  exact hval (by
    simpa [Matrix.add_apply, Matrix.smul_apply, Matrix.one_apply, hij] using hzero)

/-- The original universal assertion is false, with no additional hypotheses. -/
theorem not_bapatMonotonicity : ¬ BapatMonotonicity :=
  not_bapatMonotonicity_of_minor_identity gramWitness_minorSum

/-- Values strictly decrease between two points of the original interval. -/
theorem exists_decreasing_pair :
    ∃ ε : ℝ, 0 < ε ∧ (gramWitness + ε • 1).PosDef ∧
      ¬ (gramWitness + ε • 1).IsDiag ∧
      ∃ q₁ ∈ Set.Icc (-1 : ℝ) 1, ∃ q₂ ∈ Set.Icc (-1 : ℝ) 1,
        q₁ < q₂ ∧ qPermanent (gramWitness + ε • 1) q₂ <
          qPermanent (gramWitness + ε • 1) q₁ := by
  classical
  obtain ⟨ε, hε, hneg⟩ :=
    exists_positive_perturbation_negative gramWitness gramWitness_endpoint_negative
  have hmono := not_monotoneOn_Icc_of_hasDerivAt_neg (by norm_num : (-1 : ℝ) < 1)
    (hasDerivAt_qPermanent_one (gramWitness + ε • 1)) hneg
  simp only [MonotoneOn, not_forall, not_le] at hmono
  obtain ⟨q₁, hq₁, q₂, hq₂, hle, hrev⟩ := hmono
  have hlt : q₁ < q₂ := by
    apply lt_of_le_of_ne hle
    intro heq
    subst q₂
    exact (lt_irrefl _) hrev
  refine ⟨ε, hε, positive_perturbation_posDef gramWitness gramWitness_posSemidef hε,
    ?_, q₁, hq₁, q₂, hq₂, hlt, hrev⟩
  obtain ⟨i, j, hij, hval⟩ := gramWitness_off_diagonal
  intro hdiag
  have hzero := hdiag hij
  exact hval (by
    simpa [Matrix.add_apply, Matrix.smul_apply, Matrix.one_apply, hij] using hzero)

#print axioms gramWitness_minorSum
#print axioms gramWitness_endpoint_negative
#print axioms exists_positive_definite_counterexample
#print axioms not_bapatMonotonicity
#print axioms exists_decreasing_pair

end
end Bapat


-- Source: Bapat/Main.lean
/-!
# The exact proposed Formal Conjectures target

The target is Conjecture 1 in Section 4 of C. M. da Fonseca,
*The mu-permanent revisited*, arXiv:1804.02231.
All quantifiers are outside `answer(False)`. Positive definiteness includes
Hermitian symmetry in Mathlib.
-/

open scoped ComplexOrder

namespace BapatLal

noncomputable section

theorem qPermanent_re {n : ℕ} (A : Matrix (Fin n) (Fin n) ℂ) (q : ℝ) :
    (A.qPermanent q).re = Bapat.qPermanent A q := by
  change (Bapat.complexQPermanent A q).re = _
  exact Bapat.complexQPermanent_re A q

/-- The negative answer to the original Bapat–Lal monotonicity question. -/
theorem qPermanentMonotonicity :
    answer(False) ↔
      ∀ (n : ℕ) (A : Matrix (Fin n) (Fin n) ℂ),
        A.PosDef → ¬ A.IsDiag →
          StrictMonoOn (fun q : ℝ => (A.qPermanent q).re) (Set.Icc (-1) 1) := by
  constructor
  · intro h
    exact h.elim
  · intro h
    apply Bapat.not_bapatMonotonicity
    intro n A hpd hnd
    simpa only [qPermanent_re] using h n A hpd hnd

#print axioms qPermanentMonotonicity
#print axioms Bapat.exists_decreasing_pair

end
end BapatLal


-- Source: Bapat.lean
/-! Complete disproof of the Bapat–Lal q-permanent monotonicity conjecture. -/
