name = "bapat_lal"
version = "0.1.0"
defaultTargets = ["Bapat"]

[leanOptions]
autoImplicit = false
relaxedAutoImplicit = false

[[require]]
name = "formal_conjectures"
git = "https://github.com/google-deepmind/formal-conjectures"
rev = "89294ea02bd7cd678d59984add52cb4baef3dbf4"

[[lean_lib]]
name = "Bapat"
