"""Generate the mathlib-only single-file version from the packaged FC proof."""

from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[2]
LEAN = ROOT / "lean"
OUTPUT = ROOT / "lean4web/BapatLalLean4Web.lean"


def generate():
    visited = set()
    sources = []

    def visit(module):
        if module in visited:
            return
        visited.add(module)
        path = LEAN.joinpath(*module.split(".")).with_suffix(".lean")
        if not path.is_file():
            return
        text = path.read_text()
        for dependency in re.findall(r"^(?:public )?import (\S+)\s*$", text, re.M):
            visit(dependency)
        body = re.sub(r"^(?:public )?import [^\n]+\n", "", text, flags=re.M)
        body = re.sub(r"^(?:module|@\[expose\] public section)\s*\n", "", body, flags=re.M).strip()
        # Lean 4.35 renames these lemmas. The proof terms are unchanged.
        for old, new in (("if_pos", "ite_eq_left"), ("if_neg", "ite_eq_right"),
                         ("dif_pos", "dite_eq_left"), ("dif_neg", "dite_eq_right")):
            body = re.sub(r"\b" + old + r"\b", new, body)
        sources.append((path.relative_to(LEAN).as_posix(), body))

    visit("Bapat")
    header = '''import Mathlib

/-!
# Bapat-Lal q-permanent monotonicity: standalone Lean4Web proof

Generated by lean/scripts/make_lean4web.py from the FC-compatible proof.
Tested with Lean v4.35.0-rc3 and Mathlib
5e0c4e5239cb0a2d86d68a884bf52cfd963fce22.
The final theorems are BapatLal.qPermanentMonotonicity (Conjecture 1)
and BapatLal.qPermanentHalfLineMonotonicity (Conjecture 2).
No local project imports or Formal Conjectures dependency are needed.
-/

-- FC's answer(False) elaborates to False. This identity macro preserves that type.
macro "answer(" t:term ")" : term => pure t

#eval Lean.versionString
'''
    content = header + "\n\n".join(
        "\n-- Source: " + name + "\n" + body for name, body in sources
    ) + "\n"
    content = content.rstrip() + "\n"
    OUTPUT.write_text(content)
    print(f"Generated {OUTPUT.name}: {len(sources)} modules, {len(content.splitlines())} lines")


if __name__ == "__main__":
    generate()
